{{- template "common.secret" (list . "pipeline.secret") -}}
{{- define "pipeline.secret" -}}
data:
  {{- range $envvar, $envvarvalue := .Values.secret.data }}
  {{ $envvar }}: {{ $envvarvalue | quote }}
  {{- end }}
{{- end -}}
{{- template "common.secret" (list . "pipeline.tlssecret") -}}
{{- define "pipeline.tlssecret" -}}
metadata:
  name: {{ template "common.fullname" . }}-tls
data:
  {{- $hostname := .Values.basedomain }}
  {{ range $path, $bytes := .Files.Glob ( printf "certs/%s.crt" $hostname ) }}
  tls.crt: {{ $.Files.Get $path | b64enc }}
  {{ end }}
  {{ range $path, $bytes := .Files.Glob "certs/*.key" }}
  tls.key: {{ $.Files.Get $path | b64enc }} 
  {{ end }}
{{- end -}}
