pipeline:
  common:
    basedomains:
    - domain: us-south.devops.cloud.ibm.com
      tlsSecret: star.us-south.devops.cloud.ibm.com
      hostNameSuffix: ""
    - domain: ng.bluemix.net
      tlsSecret: star.ng.bluemix.net
      hostNameSuffix: ""
    resources:
      limits:
        cpu: 100m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    vaultcommon:
      secretPaths:
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/cd-pipeline/common_2019_04_23_08h07m17s
    configmap:
      data:
        SECGRP: GRP1PRDY
        log4js_logmet_enabled: true
        log4js_logmet_logging_host: ingest.logging.ng.bluemix.net
        log4js_logmet_logging_port: 9091
        log4js_logmet_space_id: 3f02963c-7330-4cef-b34c-1356ff3924c2
        log4js_syslog_appender_enabled: true
        log4js_syslog_appender_host: syslog.prd.ccs.ibmcloud.com
        log4js_syslog_appender_port: 6515
        log4js_syslog_appender_url: devops.ng.bluemix.net
        log4js_syslog_appender_whitelist: audit-logs
  travis-worker:
    replicas: 2
    vault:
      secretPaths:
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/cd-pipeline/travis-worker-staging_2019_04_30_16h50m37s
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/otc-components/common-rabbitmq-icd_2019_04_23_07h59m20s
    probes:
      enabled: false
    preStopCommand: "[/bin/sh, \"-c\", \"service travis-worker stop ; if [ $? -ne 0 ]; then date; while [ $? -eq 0 ]; do sleep 5; docker ps ; service travis-worker status; done ; fi ; docker system prune -f; docker volume prune -f; touch /var/log/travis-worker.done\"]"
    terminationGracePeriodSeconds: 4000  
    configmap:
      data:
        AMQP_LOGS_QUEUE_MSG_TTL: "7200000"
        QUEUE_NAME: builds.linux_ys1
        DOCKER_SSH_USER: pipeline
        DOCKER_RETRY_INTERVAL: "5"
        STATUS_UPDATE_INTERVAL: 5m
        POOL_SIZE: "9"
        HARD_TIMEOUT: 60m
        LOG_TIMEOUT: 60m
        PAYLOAD_ENCRYPT: false