us-south:
  basedomain: us-south.devops.cloud.ibm.com
  resources:
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
  vault:
    secretPaths:
    - generic/crn/v1/bluemix/public/continuous-delivery/us-south/cd-pipeline/common
  configmap:
    data:
      OTC_API_URL: http://otc-api/api/v1
      SECGRP: GRP1PRDY
      log4js_logmet_enabled: true
      log4js_logmet_logging_host: ingest.logging.ng.bluemix.net
      log4js_logmet_logging_port: 9091
      log4js_logmet_space_id: 3f02963c-7330-4cef-b34c-1356ff3924c2
      log4js_syslog_appender_enabled: true
      log4js_syslog_appender_host: syslog.prd.ccs.ibmcloud.com
      log4js_syslog_appender_port: 6515
      log4js_syslog_appender_url: devops.ng.bluemix.net
      log4js_syslog_appender_whitelist: audit-logs
  travis-worker-staging:
    replicas: 2
    vault:
      secretPaths:
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/cd-pipeline/travis-worker-staging
    configmap:
      data:
        AMQP_HOST: portal830-1.otc-pipeline-yp.ibm-16.composedb.com
        AMQP_PORT: "10830"
        AMQP_PATH: /otc-pipeline-yp
        AMQP_SSL: true
        AMQP_USER: travis
        AMQP_LOGS_QUEUE_MSG_TTL: "7200000"
        QUEUE_NAME: builds.linux_ys1
        DOCKER_SSH_USER: pipeline
        DOCKER_RETRY_INTERVAL: "5"
        STATUS_UPDATE_INTERVAL: 5m
        POOL_SIZE: "9"
        HARD_TIMEOUT: 60m
        LOG_TIMEOUT: 60m
