pipeline:
  common:
    basedomains:
    - domain: us-south.devops.cloud.ibm.com
      tlsSecret: star.us-south.devops.cloud.ibm.com
      hostNameSuffix: ""
    - domain: ng.bluemix.net
      tlsSecret: star.ng.bluemix.net
      hostNameSuffix: ""
    resources:
      limits:
        cpu: 100m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    vault:
      sidekickImageTag: 38dfea5b362e506e60becc91c9988c9d569e8014-202005112130UTC
    vaultcommon:
      secretPaths:
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/cd-pipeline/common_2019_07_31_15h44m21s
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/otc-components/common-cloudant_do_not_version
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/cd-pipeline/cloudant_iam_id_2020_07_08_14h50m03s
    probes:
      enabled: true
      liveness:
        initialDelay: 30
        periodSeconds: 15
        timeoutSeconds: 5
      readiness:
        initialDelay: 5
        periodSeconds: 15
        timeoutSeconds: 10
    configmap:
      data:
        USE_K8S: true
        SECGRP: GRP1PRDY
        CLOUDANT_ACCOUNT: '9cb9bdc9-10b0-4a27-afea-d26eadc3ddb2-bluemix'
        CLOUDANT_URL: 'https://9cb9bdc9-10b0-4a27-afea-d26eadc3ddb2-bluemix.cloudant.com'
  travis-worker:
    replicas: 2
    vault:
      secretPaths:
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/cd-pipeline/travis-worker_2019_04_25_14h46m29s
      - generic/crn/v1/bluemix/public/continuous-delivery/us-south/otc-components/common-rabbitmq-icd_2019_04_23_07h59m20s
    probes:
      enabled: false
    preStopCommand: "[/bin/sh, \"-c\", \"service travis-worker stop ; if [ $? -ne 0 ]; then date; while [ $? -eq 0 ]; do sleep 5; docker ps ; service travis-worker status; done ; fi ; docker system prune -f; docker volume prune -f; touch /var/log/travis-worker.done\"]"
    terminationGracePeriodSeconds: 4000
    configmap:
      data:
        AMQP_LOGS_QUEUE_MSG_TTL: "7200000"
        QUEUE_NAME: builds.linux_ys1
        DOCKER_SSH_USER: pipeline
        DOCKER_RETRY_INTERVAL: "5"
        STATUS_UPDATE_INTERVAL: 5m
        POOL_SIZE: "9"
        HARD_TIMEOUT: 60m
        LOG_TIMEOUT: 60m
        PAYLOAD_ENCRYPT: true