apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-component-pipeline
spec:
  params:
    - name: imageName
      description: the name of the output docker image
    - name: imageTag
      description: the tag for the output docker image
    - name: accountApiKey1416501
      description: api key for prod cluster / CR
    - name: accountApiKey1308775
      description: api key for docker build machine
    - name: accountApiKey1651315
      description: api key for dev cluster
    - name: crRegion
      description: the CR region to use
    - name: crAccountName
      description: the CR account name to use
    - name: idsToken
      description: the ids token to use to clone repos
    - name: registryUrl
      description: the CR registry URL to use
    - name: registryNamespace
      description: the CR NS to use 
    - name: componentRepo
      description: The component repo url
    - name: componentRevision
      description: The component revision
    - name: componentName
      description: The component name
    - name: clusterName
      description: The cluster name
    - name: clusterNamespace
      description: The cluster namespace
    - name: imageUrl
      description: The config repo url
    - name: environment
      description: build environment
    - name: skipBuild
      description: skip build flag
    - name: skipVA
      description: skip VA flag
    - name: skipDeploy
      description: skip deploy flag
  tasks:
  - name: build
    taskRef:
      name:  build-component
    params:
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: accountApiKey1308775
        value: $(params.accountApiKey1308775)
      - name: accountApiKey1651315
        value: $(params.accountApiKey1651315)
      - name: dockerPassword
        value: $(params.accountApiKey1416501)
      - name: idsToken
        value: $(params.idsToken)
      - name: componentRepo
        value: $(params.componentRepo)
      - name: componentRevision
        value: $(params.componentRevision)
      - name: componentName
        value: $(params.componentName)
      - name: clusterName
        value: $(params.clusterName)
      - name: clusterNamespace
        value: $(params.clusterNamespace)
      - name: imageUrl
        value: $(params.imageUrl)
      - name: environment
        value: $(params.environment)
      - name: runBaseImage
        value: us.icr.io/opentoolchain/cd-build-base:nodejs10
      - name: dockerFile
        value: ''
      - name: imageTag
        value: ''
      - name: skipBuild
        value: $(params.skipBuild)
      - name: skipVA
        value: $(params.skipVA)
      - name: skipDeploy
        value: $(params.skipDeploy)
  - name: deploy
    runAfter: [build]
    taskRef:
      name:  deploy-component
    params:
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: accountApiKey1308775
        value: $(params.accountApiKey1308775)
      - name: accountApiKey1651315
        value: $(params.accountApiKey1651315)
      - name: dockerPassword
        value: $(params.accountApiKey1416501)
      - name: idsToken
        value: $(params.idsToken)
      - name: componentRepo
        value: $(params.componentRepo)
      - name: componentRevision
        value: $(params.componentRevision)
      - name: componentName
        value: $(params.componentName)
      - name: clusterName
        value: $(params.clusterName)
      - name: clusterNamespace
        value: $(params.clusterNamespace)
      - name: imageUrl
        value: $(params.imageUrl)
      - name: environment
        value: $(params.environment)
      - name: runBaseImage
        value: us.icr.io/opentoolchain/cd-build-base:nodejs10
      - name: dockerFile
        value: ''
      - name: imageTag
        value: ''
      - name: skipBuild
        value: $(params.skipBuild)
      - name: skipVA
        value: $(params.skipVA)
      - name: skipDeploy
        value: $(params.skipDeploy)