apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-kata-update
spec:
  params:
    - name: registryRegion
      default: us-south
    - name: registryScope
      default: 'global'
    - name: useUbi
      default: "false"
  stepTemplate:
    env:
      - name: API
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: API
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: API_KEY
  workspaces:
  - name: task-pvc
    mountPath: /workspace
  steps:
  - name: run-base
    image: icr.io/continuous-delivery/pipeline/pipeline-base-image:latest
    imagePullPolicy: Always
    env:
      - name: HOME
        value: "/root"
      - name: REGISTRY_REGION
        value: $(params.registryRegion)
      - name: DOCKER_HOST
        value: "unix:///var/run/docker.sock"
      - name: REGISTRY_SCOPE
        value: $(params.registryScope)
      - name: USE_UBI
        value: $(params.useUbi)
      - name: DOCKERFILE
        value: 3x_Dockerfile_ubi
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        export HOME=/root
        [ -f /root/.nvm/nvm.sh ] && source /root/.nvm/nvm.sh
        set -e
        ibmcloud config --check-version=false
        ibmcloud plugin install -f container-registry
        ibmcloud login -a ${API} -r ${REGISTRY_REGION} --apikey ${API_KEY}
        ibmcloud cr region-set ${REGISTRY_SCOPE}

        DOCKERFILE=${DOCKERFILE}
        echo "Building using local Docker"
        echo "Dockerfile: ${DOCKERFILE}"

        echo "Checking latest version"
        docker pull registry.access.redhat.com/ubi7/ubi:latest
        sleep 5
        tarr=$(docker image inspect registry.access.redhat.com/ubi7/ubi:latest | jq -r '.[].Config.Labels.url')

        echo "Comparing with current ubi7 image"
        curr=$(cat ${KATA_DIRECTORY}/Dockerfile | grep ubi7)

        IFS='/' read -ra tarr_temp <<< "$tarr"
        IFS=':' read -ra curr_temp <<< "$curr"

        target=${tarr_temp[${#tarr_temp[@]} - 1]}
        current=${curr_temp[${#curr_temp[@]} - 1]}

        echo target version=$target
        echo current version=$current
    
        if ! [[ "$current" == target ]] ;
        then
          echo "get current kata version"
          current_kata_version=$(yq --yaml-output '.spec.template.spec.containers[0].image' kata-deploy/config/200-kata-deploy.yaml)
          echo $current_kata_version
          #IFS='-' read -ra curr_kata <<< "$current_kata_version"

          #new_kata_version=${curr_kata[0]}-$((${curr_kata[1]}+1))=
          #sed -i '' -e "s/$current_kata_version/$new_kata_version/g" "${KATA_DIRECTORY}/config/200-kata-deploy.yaml"
          #sed -i '' -e "s/$current_kata_version/$new_kata_version/g" "${KATA_DIRECTORY}/config/300-kata-cleanup.yaml"


          #DOCKER_BUILDKIT=0 .{KATA_DIRECTORY}/build.sh ${new_kata_version}

          #docker tag ${IMAGE_NAME}:latest icr.io/continuous-delivery/pipeline/kata-deploy:${new_kata_version}
          #docker push icr.io/continuous-delivery/pipeline/kata-deploy:${new_kata_version}
        fi 