apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: get-kata-update-trigger
spec:
  params:
    # CD integration
    - name: api
      description: the ibmcloud api
      default: https://cloud.ibm.com

  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        API: $(params.api)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY_1416501)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: get-kata-update-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce

    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        #generateName: $(params.source_branch)-base-run
        name: get-kata-update-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "get-kata-update-trigger"
      spec:
        pipelineRef:
          name: pipeline-get-kata-update
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: get-kata-update-$(uid)-pvc
        serviceAccountName: docker-build-sa
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: get-kata-update-binding
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: get-kata-update
spec:
  triggers:
    - binding:
        name: get-kata-update-binding
      template:
        name: get-kata-update-trigger
