apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: hc-jp-osa-trigger-dev
spec:
  params:
    - name: script_repo
    - name: script_branch
    - name: script_directory
    - name: config_repo
    - name: config_branch
    - name: config_directory
    - name: clusterNamespace
    - name: clusterName1
    - name: skipDeploy1
    - name: clusterName2
    - name: skipDeploy2
    - name: clusterName3
    - name: skipDeploy3

    # CD integration
    - name: apikey
      description: the ibmcloud api key
    - name: toolchainRegion
      description: the ibmcloud region containing the toolchain referencing the repository
      default: us-south

  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        REGION: $(params.toolchainRegion)
        IDS_USER: $(params.IDS_USER)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY_1416501)
        DEPLOY_API_KEY: $(params.API_KEY_1416501)
        IDS_TOKEN: $(params.IDS_TOKEN)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name:  $(params.script_branch)-hc-jp-osa-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(params.script_branch)-hc-jp-osa-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "hc-jp-osa-trigger-dev"
      spec:
        pipelineRef:
          name: pipeline-hc
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: $(params.script_branch)-hc-jp-osa-$(uid)-pvc
        serviceAccountName: docker-build-sa
        params:
          - name: script_repo
            value: $(params.script_repo)
          - name: script_branch
            value: $(params.script_branch)
          - name: script_directory
            value: $(params.script_directory)
          - name: config_repo
            value: $(params.config_repo)
          - name: config_branch
            value: $(params.config_branch)
          - name: config_directory
            value: $(params.config_directory)
          - name: clusterNamespace
            value: $(params.clusterNamespace)
          - name: clusterName1
            value: $(params.clusterName1)
          - name: skipDeploy1
            value: $(params.skipDeploy1)
          - name: clusterName2
            value: $(params.clusterName2)
          - name: skipDeploy2
            value: $(params.skipDeploy2)
          - name: clusterName3
            value: $(params.clusterName3)
          - name: skipDeploy3
            value: $(params.skipDeploy3)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hc-jp-osa-binding
spec:
  params:
    - name: script_repo
      value: "https://github.ibm.com/org-ids/cd-pipeline-kubernetes.git"
    - name: script_branch
      value: "master"
    - name: script_directory
      value: "cd-pipeline-kubernetes"
    - name: config_repo
      value: "https://github.ibm.com/org-ids/pipeline-config.git"
    - name: config_branch
      value: "master"
    - name: config_directory
      value: "pipeline-config"
    - name: clusterNamespace
      value: opentoolchain
    - name: clusterName1
      value: otc-osa21-prod
    - name: skipDeploy1
      value: "false"
    - name: clusterName2
      value: otc-osa22-prod
    - name: skipDeploy2
      value: "false"
    - name: clusterName3
      value: otc-osa23-prod
    - name: skipDeploy3
      value: "false"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hc-jp-osa
spec:
  triggers:
    - binding:
        name: hc-jp-osa-binding
      template:
        name: hc-jp-osa-trigger-dev
