apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-pii
spec:
  params:
    - name: source_directory
    - name: runBaseImage
    - name: environment
      default: 'development'
    - name: javaPattern
      default: 'false'
    - name: nls_folder_pattern
    - name: nls_file_pattern
  workspaces:
  - name: task-pvc
    mountPath: /workspace 
  steps:
  - name: run-pii
    image: $(params.runBaseImage)
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: SOURCE_DIRECTORY
        value: $(params.source_directory)
      - name: SKIP
        value: "false"
      - name: JAVA_PATTERN
        value: $(params.javaPattern)
      - name: NLS_FILE_PATTERN
        value: $(params.nls_file_pattern)
      - name: NLS_FOLDER_PATTERN
        value: $(params.nls_folder_pattern)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        export HOME=/root
        #set -e
        if [ "${SKIP}" == true ]; then
          echo "Skipping PII"
          exit 0
        fi
        cd "${SOURCE_DIRECTORY}"
        if [ "$JAVA_PATTERN" = true ]; then
          export NLS_FOLDER_PATTERN=resources
          export NLS_FILE_PATTERN=Language_en.properties
        fi
        pii/run
