apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deployment-list
spec:
  params:
    - name: source_directory
    - name: deployBaseImage
      default: us.icr.io/opentoolchain/cd-deploy-base:deploy
    - name: environment
      default: 'development'
    - name: prodRepos
      default: 'None'
  stepTemplate:
    env:
      - name: IDS_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: IDS_TOKEN
  workspaces:
  - name: task-pvc
    mountPath: /workspace 
  steps:
  - name: get-deployment-list
    image: $(params.deployBaseImage)
    imagePullPolicy: Always
    env:
      - name: HOME
        value: "/root"
      - name: SOURCE_DIRECTORY
        value: $(params.source_directory)
      - name: PROD_REPOS
        value: $(params.prodRepos)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        export HOME=/root
        [ -f /root/.nvm/nvm.sh ] && source /root/.nvm/nvm.sh
        DIR=$( mktemp -d )
        cd $DIR

        PROD_REPOS=blade-pipeline-broker,otc-github-relay-pub,otc-github-relay-sub,pipeline-artifact-repository-service,pipeline-consumption,pipeline-event-service,pipeline-log-service,pipeline-service,pipeline-ui,private-worker-service,travis-worker-go,pipeline-support-service

        printf 'Deliver changes for:\n' 

        IFS=',' read -ra REPOS <<<$PROD_REPOS
        for REPO in ${REPOS[@]}; do
            REPO_URL=https://github.ibm.com/org-ids/${REPO}
            REPO_URL_AUTH=https://x-oauth-basic:$IDS_TOKEN@github.ibm.com/org-ids/${REPO}.git
            git clone -b integration "$REPO_URL_AUTH" >/dev/null 2>&1
            pushd $REPO >/dev/null 2>&1
            LAST_TAG=$( git tag --list 'prod-*' | tail -1 )
            OLD_DEPLOY=$( git rev-list -n 1 $LAST_TAG )
            REV=$( git rev-list -n 1 HEAD )
            if [ $OLD_DEPLOY = $REV ]; then
                printf "$REPO : no change"'\n' 
            else
                printf "$REPO : ${REPO_URL}/compare/${LAST_TAG}...${REV}"'\n' 
            fi
            popd >/dev/null 2>&1
        done
