apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-hc
spec:
  params:
    - name: source_directory
    - name: script_directory
    - name: clusterName
    - name: clusterNamespace
      default: opentoolchain
    - name: skipDeploy
      default: 'false'
  stepTemplate:
    env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: DEPLOY_API_KEY
      - name: REGION
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: REGION
  workspaces:
  - name: task-pvc
    mountPath: /workspace 
  steps:
  - name: health-check
    image: ibmcom/pipeline-base-image:2.9
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: SOURCE_DIRECTORY
        value: $(params.source_directory)
      - name: SCRIPT_DIRECTORY
        value: $(params.script_directory)
      - name: SKIP
        value: $(params.skipDeploy)
      - name: CLUSTER_NAME
        value: $(params.clusterName)
      - name: CLUSTER_NAMESPACE
        value: $(params.clusterNamespace)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
       set -e
        if [ "${SKIP}" == true ]; then
          echo "Skipping Deploy for $CLUSTER_NAME"
          exit 0
        fi

        ibmcloud config --check-version=false
        ibmcloud plugin install -f container-service

        echo "Current Directory: $(pwd)"

        echo Logging into Deployment account
        ibmcloud login --apikey ${API_KEY} -r ${REGION} 

        set +e
        function cluster_config() {
            # 1 - cluster name
            for iteration in {1..30}
            do
                echo "Running cluster config for cluster $1: $iteration / 30"
                ibmcloud ks cluster config --cluster $1
                if [[ $? -eq 0 ]]; then
                    return 0
                else
                    echo "Cluster config for $1 failed. Trying again..."
                    sleep 5
                fi
            done
            return 1
        }
        cluster_config ${CLUSTER_NAME}
        set -e

        chmod a+x ${SCRIPT_DIRECTORY}/scripts/healthcheck.sh 
        ${SCRIPT_DIRECTORY}/scripts/healthcheck.sh ${CLUSTER_NAMESPACE} ${SOURCE_DIRECTORY}/cr/components.txt