apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: asoc-send-slack-task
spec:
  params:
    - name: componentName
      description: the name of the component/broker
    - name: branchName
      description: the name of the branch being scanned
  stepTemplate:
    env:
      - name: APPSCAN_APP_ID
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: APPSCAN_APP_ID
      - name: APPSCAN_APP_KEY_ID
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: APPSCAN_APP_KEY_ID
      - name: APPSCAN_API_KEY_SECRET
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: APPSCAN_API_KEY_SECRET
      - name: APPSCAN_API_KEY_SECRET
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: APPSCAN_API_KEY_SECRET
      - name: SLACK_WEBHOOK
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: SLACK_WEBHOOK
  workspaces:
  - name: task-pvc
    mountPath: /workspace 
  steps:
    - name: slack
      image: ibmcom/pipeline-base-image:2.6
      imagePullPolicy: IfNotPresent
      env:
        - name: HOME
          value: "/root"
        - name: WORKSPACE
          value: "/workspace"
        - name: APPSCAN_NAME
          value: $(params.componentName)
        - name: BRANCH_NAME
          value: $(params.branchName)
      workingDir: /workspace
      command: ["/bin/bash", "-c"]
      args:
        - |
          #!/bin/bash
          export HOME=/root && [ -f /root/.nvm/nvm.sh ] && chmod +x /root/.nvm/nvm.sh && source /root/.nvm/nvm.sh 
          cd $HOME
          cp -R /workspace/otc-deploy .
          export WORKSPACE=$HOME
          export API_KEY_ID="$APPSCAN_APP_KEY_ID"
          export API_KEY_SECRET="$APPSCAN_API_KEY_SECRET"
          export APPSCAN_APP_ID="$APPSCAN_APP_ID"
          export SCAN_NAME="$APPSCAN_NAME"
          export SLACK_WEBHOOK="$SLACK_WEBHOOK"
          set +x

          chmod +x ./otc-deploy/k8s/scripts/asoc/send_report_to_slack_pipeline_apps.sh
          cd ./otc-deploy/k8s/scripts/asoc/
          ./send_report_to_slack_pipeline_apps.sh


