apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag-deployment
spec:
  params:
    - name: source_directory
    - name: deployBaseImage
      default: us.icr.io/opentoolchain/cd-deploy-base:deploy
    - name: environment
      default: 'development'
    - name: prodRepos
      default: 'None'
  stepTemplate:
    env:
      - name: IDS_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: IDS_TOKEN
  workspaces:
  - name: task-pvc
    mountPath: /workspace 
  steps:
  - name: prod-cloning
    image: $(params.deployBaseImage)
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: SOURCE_DIRECTORY
        value: $(params.source_directory)
      - name: PROD_REPOS
        value: $(params.prodRepos)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        export HOME=/root
        [ -f /root/.nvm/nvm.sh ] && source /root/.nvm/nvm.sh

        if [ -r $SOURCE_DIRECTORY/cr/components.txt ]; then
          PROD_REPOS="$( <$SOURCE_DIRECTORY/cr/components.txt )"
        fi
        
        mkdir -p tmp_info ; cd tmp_info

        if [ "$PROD_REPOS" = None ]; then
            echo "Pipeline microservice configuration updates" 
            exit 0
        fi

        IFS=',' read -ra REPOS <<<$PROD_REPOS
        for REPO in ${REPOS[@]}; do
            if [ $REPO == "pgbouncer" ]; then
              continue
            fi
            echo Cloning repo $REPO
            REPO_URL_AUTH=https://x-oauth-basic:$IDS_TOKEN@github.ibm.com/org-ids/${REPO}.git
            git clone -b integration "$REPO_URL_AUTH"
        done
  - name: tag-chglog
    image: icr.io/continuous-delivery/util-images/chglog-image:1.0
    imagePullPolicy: Always
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        set -e
        [ ! -d tmp_info ] && exit 0
        REPO_URL_AUTH=https://x-oauth-basic:$IDS_TOKEN@github.ibm.com/org-ids/pipeline-changelog.git
        git clone "$REPO_URL_AUTH" --single-branch
        cd tmp_info

        git config --global user.email "empty@ibm.com"

        TAG=prod-$( date +%Y%m%d-%H%M )
        echo 'tagging with' $TAG

        for REPO in *; do
            mkdir -p /workspace/pipeline-changelog/${REPO}
            echo Tagging repo $REPO
            REPO_URL=https://github.ibm.com/org-ids/${REPO}
            pushd $REPO
            GIT_COMMIT=$(git rev-parse --verify HEAD)
            SECOND_LATEST_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1))
            git tag "$TAG" -m "Empty Message"
            cp -r $HOME/.chglog .
            sed -i "s#dummyURL#${REPO_URL}#" .chglog/config.yml
            git-chglog $TAG.. > /workspace/pipeline-changelog/${REPO}/${GIT_COMMIT}.md

            TITLE="Changelog in the tag message.\n\n[Comparison against previous tag](https://github.ibm.com/org-ids/${REPO}/compare/${SECOND_LATEST_TAG}...${TAG}) . \n"
            sed -i "1d;2s#^#${TITLE}\n#" /workspace/pipeline-changelog/${REPO}/${GIT_COMMIT}.md

            rm -rf .chglog
            git tag "$TAG" ${TAG}^{} -f -F /workspace/pipeline-changelog/${REPO}/${GIT_COMMIT}.md
            sed -i "1,4d" /workspace/pipeline-changelog/${REPO}/${GIT_COMMIT}.md
            popd
        done
        cd ../pipeline-changelog
        git add .
        git commit -m "Changes in ${TAG}"
        git push origin master
  - name: tag-deployment
    image: $(params.deployBaseImage)
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        export HOME=/root
        [ -f /root/.nvm/nvm.sh ] && source /root/.nvm/nvm.sh

        [ ! -d tmp_info ] && exit 0
        cd tmp_info

        for REPO in *; do
            pushd $REPO
            echo Pushing to repo $REPO
            git push --tags
            popd
        done
