apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: auto-deploy-au-syd
spec:
  params:
    - name: syd-auto-deploy-token
      description: the token used to call generic webhook url
    - name: syd-auto-deploy-url
      description: the generic webhook url
  steps:
    - name: auto-deploy
      image: ibmcom/pipeline-base-image:2.8
      imagePullPolicy: Always
      env:
        - name: AUTO_DEPLOY_TOKEN
          value: $(params.syd-auto-deploy-token)
        - name: AUTO_DEPLOY_URL
          value: $(params.syd-auto-deploy-url)
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "checking existence of syd-auto-deploy-url"
          if [ -z "$AUTO_DEPLOY_URL" ] && [ -z "$AUTO_DEPLOY_TOKEN" ]; then
                echo "syd-auto-deploy-token or syd-auto-deploy-url is empty, cannot auto deploy to au-syd"
          else
                echo "Triggering auto deployment to AU-SYD"
                RESPONSE=$(curl --request POST $AUTO_DEPLOY_URL -H "au-syd-token:$AUTO_DEPLOY_TOKEN")

                PIPELINE_RUN_ID=$(jq --raw-output ".id" <<< "$RESPONSE")

                if [[ ! "$PIPELINE_RUN_ID" ]]; then
                    echo "Failed: $RESPONSE"
                else 
                    echo "Deploying to AU_SYD at pipelinerun $PIPELINE_RUN_ID"
                fi
          fi
