apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-mocha
spec:
  params:
    - name: source-directory
    - name: registry-url
      default: us.icr.io
    - name: registry-namespace
      default: opentoolchain
    - name: registry-region
      default: us-south
    - name: image-name
      default: ''
    - name: image-tag
    - name: image-url
    - name: build-cluster
      default: otc-dal12-build
    - name: docker-file
    - name: docker-username
      default: iamapikey
    - name: run-base-image
    - name: extra-docker-opts
      default: --no-cache
    - name: environment
      default: 'development'
    - name: artifactory-token-base64
      default: ''
    - name: artifactory-id
      default: ''
    - name: console-auth-token
      default: ''
    - name: skip-mocha
      default: 'true'
  stepTemplate:
    env:
      - name: API
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: API
      - name: REGION
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: REGION
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: API_KEY
      - name: DOCKER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: API_KEY
      - name: API_KEY_1308775
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: API_KEY_1308775
      - name: BUILD_CLUSTER_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: API_KEY_1308775
      - name: TOOLCHAIN_ID
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: TOOLCHAIN_ID
      - name: IDS_USER
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: IDS_USER
      - name: IDS_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: IDS_TOKEN
  workspaces:
  - name: task-pvc
    mountPath: /workspace 
  steps:
  - name: run-base
    image: $(params.run-base-image)
    imagePullPolicy: Always
    env:
      - name: HOME
        value: "/root"
      - name: IMAGE_NAME
        value: $(params.image-name)
      - name: IMAGE_TAG
        value: $(params.image-tag)
      - name: APPLICATION_VERSION
        value: $(params.image-tag)
      - name: IMAGE_URL
        value: $(params.image-url)
      - name: REGISTRY_URL
        value: $(params.registry-url)
      - name: REGISTRY_NAMESPACE
        value: $(params.registry-namespace)
      - name: REGISTRY_REGION
        value: $(params.registry-region)
      - name: SOURCE_DIRECTORY
        value: $(params.source-directory)
      - name: DOCKERFILE
        value: $(params.docker-file)
      - name: DOCKER_IMAGE
        value: $(params.run-base-image)
      - name: DOCKER_USERNAME
        value: $(params.docker-username)
      - name: EXTRA_DOCKER_OPTS
        value: $(params.extra-docker-opts)
      - name: BUILD_CLUSTER
        value: $(params.build-cluster)
      - name: ENVIRONMENT
        value: $(params.environment)
      # used for pipeline-ui build
      - name: ARTIFACTORY_TOKEN_BASE64
        value: $(params.artifactory-token-base64)
      - name: ARTIFACTORY_ID
        value: $(params.artifactory-id)
      - name: CONSOLE_AUTH_TOKEN
        value: $(params.console-auth-token)
      # can we get rid of this?
      - name: OPERATOR_SDK
        value: ''
      - name: SKIP
        value: $(params.skip-mocha)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        export HOME=/root
        [ -f /root/.nvm/nvm.sh ] && source /root/.nvm/nvm.sh
        set -e
        if [ "${SKIP}" == true ]; then
          echo "Skipping Mocha tests"
          exit 0
        fi
        cd "${SOURCE_DIRECTORY}"
        if [ -s /work/component/dependenciesResolver.sh ] ; then sh /work/component/dependenciesResolver.sh ; fi
        npm install -f
        if [ -s /work/component/extraSteps.sh ] ; then sh /work/component/extraSteps.sh ; fi
        npm list
        npm test

