apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-hc
spec:
  params:
    - name: source-directory
    - name: script-directory
    - name: cluster-name
    - name: cluster-namespace
      default: opentoolchain
    - name: skip-deploy
      default: 'false'
  stepTemplate:
    env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: DEPLOY_API_KEY
      - name: REGION
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: REGION
  workspaces:
  - name: task-pvc
    mountPath: /workspace 
  steps:
  - name: health-check
    image: ibmcom/pipeline-base-image:2.8
    imagePullPolicy: Always
    env:
      - name: HOME
        value: "/root"
      - name: SOURCE_DIRECTORY
        value: $(params.source-directory)
      - name: SCRIPT_DIRECTORY
        value: $(params.script-directory)
      - name: SKIP
        value: $(params.skip-deploy)
      - name: CLUSTER_NAME
        value: $(params.cluster-name)
      - name: CLUSTER_NAMESPACE
        value: $(params.cluster-namespace)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
       set -e
        if [ "${SKIP}" == true ]; then
          echo "Skipping Deploy for $CLUSTER_NAME"
          exit 0
        fi

        ibmcloud config --check-version=false
        ibmcloud plugin install -f container-service

        echo "Current Directory: $(pwd)"

        echo Logging into Deployment account
        ibmcloud login --apikey ${API_KEY} -r ${REGION} 

        ibmcloud ks cluster config  --cluster ${CLUSTER_NAME} --skip-rbac

        chmod a+x ${SCRIPT_DIRECTORY}/scripts/healthcheck.sh 
        ${SCRIPT_DIRECTORY}/scripts/healthcheck.sh ${CLUSTER_NAMESPACE} ${SOURCE_DIRECTORY}/cr/components.txt