apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: open-cr
spec:
  params:
    - name: source_directory
    - name: deployBaseImage
      default: us.icr.io/opentoolchain/cd-deploy-base:deploy
    - name: environment
      default: 'development'
    - name: snUrl
      default: 'https://watson.service-now.com'
    - name: deployClusters
      default: ''
    - name: deployChannel
      default: '#devops-otc-deployment'
    - name: tocChannel
      default: '#devops-cd-cie'
    - name: e2eToolchainId
      default: ''
    - name: e2eApplication
      default: 'Pipeline'
    - name: e2eBuildId
      default: ''
  stepTemplate:
    env:
      - name: PIPELINE_TRIGGERING_USER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: API_KEY
      - name: SN_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: SN_TOKEN
      - name: SLACK_DEPLOY_HOOK
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: SLACK_DEPLOY_HOOK
      - name: SLACK_TOC_HOOK
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: SLACK_TOC_HOOK
  workspaces:
  - name: task-pvc
    mountPath: /workspace 
  steps:
  - name: open-cr
    image: $(params.deployBaseImage)
    imagePullPolicy: Always
    env:
      - name: HOME
        value: "/root"
      - name: DEPLOY_TARGET
        value: $(params.environment)
      - name: DEPLOY_CLUSTERS
        value: $(params.deployClusters)
      - name: SN_URL
        value: $(params.snUrl)
      - name: SOURCE_DIRECTORY
        value: $(params.source_directory)
      - name: ENVIRONMENT
        value: $(params.environment)
      - name: E2E_TOOLCHAIN_ID
        value: $(params.e2eToolchainId)
      - name: E2E_APPLICATION
        value: $(params.e2eApplication)
      - name: E2E_BUILD_ID
        value: $(params.e2eBuildId)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        export HOME=/root
        [ -f /root/.nvm/nvm.sh ] && source /root/.nvm/nvm.sh
        set -e
        cd "${SOURCE_DIRECTORY}"
        mkdir -p cr/$ENVIRONMENT
        ID_FILE=cr/$ENVIRONMENT/cr_id
        if [ -r cr/$ENVIRONMENT/cr_id ]; then
          echo "Already a CR open for $ENVIRONMENT"
          exit 1
        fi

        ibmcloud config --check-version=false
        ibmcloud login -a cloud.ibm.com -r us-south --apikey ${API_KEY}
        BEARER=$( ibmcloud iam oauth-tokens --output json | jq -r .iam_token )

        SYSTEM="continuous-delivery-pipeline"
        CRN="crn:v1:bluemix:public::$ENVIRONMENT::::"
        PURPOSE="Continuous Delivery deployment of Pipeline to public environment ($DEPLOY_TARGET: $DEPLOY_CLUSTERS)."

        if [ -r /workspace/deployment.txt ]; then
          DEPLOY_PACKAGE="$( </workspace/deployment.txt )"
        else
          DEPLOY_PACKAGE="https://github.ibm.com/org-ids/pipeline-config/tree/$(git rev-parse HEAD)"
        fi

        if [[ "$PIPELINE_TRIGGERING_USER" =~ .+@.+\..+ && "$PIPELINE_TRIGGERING_USER" != "idsorg@us.ibm.com" ]]; then
            ASSIGNED_TO="$PIPELINE_TRIGGERING_USER"
        else
            ASSIGNED_TO="$(git log -1 --pretty=format:'%ae')"
        fi

        S_DATE=$(( $(date +%s) + 5 ))
        E_DATE=$(( $(date +%s) + 900 ))

        export TMP=/tmp/tmp_$$.json

        # tag message adds link to ServiceNow query using deploy commit hash in the description field
        cat - >"$TMP" <<HERE
        {
          "assignedto": "$ASSIGNED_TO",
          "system": "$SYSTEM",
          "impact": "N/A",
          "outageduration": "0 00:00:00",
          "priority": "moderate",
          "environment": "$CRN",
          "purpose": "$PURPOSE",
          "description": "$PURPOSE\nDescription/Plan: Delivering changes for:\n$DEPLOY_PACKAGE",
          "backoutplan": "Revert changes and re-deploy.",
          "plannedstart": "$(date -u -d@${S_DATE} "+%Y-%m-%d %H:%M:%S")",
          "plannedend": "$(date -u -d@${E_DATE} "+%Y-%m-%d %H:%M:%S")", 
          "deploymentready": "yes",
          "type": "standard"
        }
        HERE

        RESPONSE=$(curl --request POST -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            --data "@$TMP" "$SN_URL/api/ibmwc/v2/change/create" \
            --silent --show-error)

        CR_ID=$(jq --raw-output ".result.number | select (.!=null)" <<< "$RESPONSE")

        if [[ ! "$CR_ID" ]]; then
            echo "$RESPONSE"
            exit 1
        fi

        echo "ServiceNow change request opened: $SN_URL/nav_to.do?uri=change_request.do?sysparm_query=number=$CR_ID"
        echo $CR_ID > $ID_FILE
        git config --global user.email "idsorg@us.ibm.com"
        git config --global user.name "IDS Organization"
        git config --global push.default matching
        git add -A $ID_FILE
        git commit -m "${PURPOSE}"

        n=0
        rc=0
        ORIG_DIR=$(pwd)
        until [ $n -ge 5 ]
        do
          git push
          rc=$?
          if [[ $rc == 0 ]]; then 
            break;
          fi
          n=$[$n+1]
          git pull
        done

        echo "Checking ServiceNow change request state..."

        RESPONSE=$(curl -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            "$SN_URL/api/ibmwc/v2/change/$CR_ID/read" \
            --silent --show-error)

        CR_STATE=$(jq --raw-output ".result.state | select (.!=null)" <<< "$RESPONSE")

        if [[ ! "$CR_STATE" ]]; then
            echo "$RESPONSE"
            exit 1
        fi

        if [[ "$CR_STATE" == "Scheduled" ]]; then
            echo "ServiceNow change request is in 'Scheduled' state."
        else
            echo "ServiceNow change request is not in 'Scheduled' state (state: $CR_STATE)"
            exit 1
        fi
        
        # add au-syd E2E tests via a CTASK
        E2E_TOOLCHAIN_ID=${E2E_TOOLCHAIN_ID:-d5c0676c-55ed-4c25-b763-60b7afd64c87}
        curl -s -X GET "https://dlms.us-south.devopsinsights.cloud.ibm.com/v3/toolchainids/$E2E_TOOLCHAIN_ID/buildartifacts/$E2E_APPLICATION/builds?limit=500" \
          -H  "accept: */*" \
          -H "Authorization: $BEARER" >/workspace/tmp_doi.json
        BUILD_ID=$( jq -r '.[].build_id' /workspace/tmp_doi.json | sort | grep integration | tail -1 )
        E2E_BUILD_ID=${E2E_BUILD_ID:-$BUILD_ID}
        E2E_STAGE_ENVIRONMENT=au-syd
        SUMMARY=$( curl -s -X GET "https://dlms.us-south.devopsinsights.cloud.ibm.com/v3/toolchainids/$E2E_TOOLCHAIN_ID/buildartifacts/$E2E_APPLICATION/builds/$E2E_BUILD_ID/summaries?latest_only=true&environment_name=$E2E_STAGE_ENVIRONMENT" \
          -H  "accept: */*" \
          -H "Authorization: $BEARER" | jq . | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))' )
        cat - >"$TMP" <<HERE
        {
          "required": "required",
          "system": "$SYSTEM",
          "shortdescription": "Staging test results",
          "description": "Toolchain: $E2E_TOOLCHAIN_ID\nApplication: $E2E_APPLICATION\nBuild id: $E2E_BUILD_ID\nEnvironment: $E2E_STAGE_ENVIRONMENT",
          "data": $SUMMARY
        }
        HERE
        RESPONSE=$(curl --request POST -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            --data "@$TMP" "$SN_URL/api/ibmwc/v2/change/$CR_ID/task/create" \
            --silent --show-error)

        CTASK_ID=$(jq --raw-output ".result.number | select (.!=null)" <<< "$RESPONSE")

        if [[ ! "$CTASK_ID" ]]; then
            echo "$RESPONSE"
            exit 1
        fi
        PAYLOAD=$(jq --null-input "$(cat <<HERE
        {
            state: "Closed"
        }
        HERE
        )")

        RESPONSE=$(curl --request PUT -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            --data "$PAYLOAD" "$SN_URL/api/ibmwc/v2/change/$CR_ID/task/$CTASK_ID/update" \
            --silent --show-error)

        CTASK_ID=$(jq --raw-output ".result.number | select (.!=null)" <<< "$RESPONSE")

        if [[ ! "$CTASK_ID" ]]; then
            echo "$RESPONSE"
            exit 1
        fi
        PAYLOAD=$(jq --null-input "$(cat <<HERE
        {
            worknotes: "Ready to go"
        }
        HERE
        )")

        sleep 4

        RESPONSE=$(curl --request PUT -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            --data "$PAYLOAD" "$SN_URL/api/ibmwc/v2/change/$CR_ID/implement" \
            --silent --show-error)
        
        echo "Checking ServiceNow change request state..."

        RESPONSE=$(curl -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            "$SN_URL/api/ibmwc/v2/change/$CR_ID/read" \
            --silent --show-error)

        CR_STATE=$(jq --raw-output ".result.state | select (.!=null)" <<< "$RESPONSE")
        echo "ServiceNow change request is in $CR_STATE state."

  - name: notify-slack
    image: $(params.deployBaseImage)
    imagePullPolicy: Always
    env:
      - name: HOME
        value: "/root"
      - name: DEPLOY_TARGET
        value: $(params.environment)
      - name: DEPLOY_CLUSTERS
        value: $(params.deployClusters)
      - name: URL
        value: $(params.snUrl)
      - name: SOURCE_DIRECTORY
        value: $(params.source_directory)
      - name: ENVIRONMENT
        value: $(params.environment)
      - name: SLACK_DEPLOY_CHANNEL
        value: $(params.deployChannel)
      - name: SLACK_TOC_CHANNEL
        value: $(params.tocChannel)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        export HOME=/root
        [ -f /root/.nvm/nvm.sh ] && source /root/.nvm/nvm.sh
        set -e
        set -x
        cd "${SOURCE_DIRECTORY}"
        ID_FILE=cr/$ENVIRONMENT/cr_id
        SN_TICKET_ID=$(<$ID_FILE)
        
        
        NOTICE_TEXT="Continuous Delivery deployment of Pipeline to public environment ($DEPLOY_TARGET: $DEPLOY_CLUSTERS)."

        ICON=${SN_ICON:=":-cloud-:"}
        SLACK_USERNAME=${SN_SLACK_USERNAME:="Deployment Notification"}

        cat << EOF > message.json
        {
          "channel": "${SLACK_DEPLOY_CHANNEL}",
          "text": "${NOTICE_TEXT} \n\nThe TOC has been notified in the *#devops-cd-cie* channel.",
          "username": "${SLACK_USERNAME}", 
          "icon_emoji": "${ICON}",
          "attachments": [
            {
              "title": "ServiceNow",
              "type": "mrkdwn",
              "text": "ChangeRequest ticket opened: <${URL}/nav_to.do?uri=change_request.do?sysparm_query=number=${SN_TICKET_ID}|${SN_TICKET_ID}>"
            }
          ]
        }
        EOF

        curl -X POST -H "Content-Type: application/json" \
            -d @message.json \
            ${SLACK_DEPLOY_HOOK}

        cat << EOF > message.json
        {
          "channel": "${SLACK_TOC_CHANNEL}",
          "text": "<!subteam^S1SLXH3PE> : ${NOTICE_TEXT}",
          "username": "${SLACK_USERNAME}", 
          "icon_emoji": "${ICON}",
          "attachments": [
            {
              "title": "ServiceNow",
              "type": "mrkdwn",
              "text": "ChangeRequest ticket opened: <${URL}/nav_to.do?uri=change_request.do?sysparm_query=number=${SN_TICKET_ID}|${SN_TICKET_ID}>"
            }
          ]
        }
        EOF
        #Post to devops-cd-cie channel. The <!subteam^S1SLXH3PE> string below sends the message to the user group @toc 
        curl -X POST -H "Content-Type: application/json" \
            -d @message.json \
            ${SLACK_TOC_HOOK}

