apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: blade-ubi-trigger-dev
spec:
  params:
    - name: source-repo
    - name: source-branch
    - name: source-directory
    - name: charts-repo
    - name: charts-branch
    - name: charts-directory
    - name: config-repo
    - name: config-branch
    - name: config-directory
    - name: image-url
    - name: cluster-name
    - name: cluster-namespace
    - name: skip-va
    - name: skip-deploy
    - name: helm-options

    # CD integration
    - name: api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: api-key
      description: the ibmcloud api key
    - name: toolchain-region
      description: the ibmcloud region containing the toolchain referencing the repository
      default: us-south
    - name: resource-group
      description: the ibmcloud resource group containing the toolchain referencing the repository
      default: default
    - name: toolchain-id
      description: The IBM Cloud Kubernetes cluster region

  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        API: $(params.api)
        REGION: $(params.toolchain-region)
        RESOURCE_GROUP: $(params.resource-group)
        TOOLCHAIN_ID: $(params.toolchain-id)
        IDS_USER: $(params.IDS_USER)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY_1416501)
        API_KEY_1308775: $(params.API_KEY_1308775)
        API_KEY_1651315: $(params.API_KEY_1651315)
        DEPLOY_API_KEY: $(params.API_KEY_1651315)
        IDS_TOKEN: $(params.IDS_TOKEN)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: $(params.source-branch)-blade-ubi-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(params.source-branch)-blade-ubi-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "blade-ubi-trigger-dev"
      spec:
        pipelineRef:
          name: pipeline-ci-ubi
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: $(params.source-branch)-blade-ubi-$(uid)-pvc
        serviceAccountName: docker-build-sa
        params:
          - name: source-repo
            value: $(params.source-repo)
          - name: source-branch
            value: $(params.source-branch)
          - name: source-directory
            value: $(params.source-directory)
          - name: charts-repo
            value: $(params.charts-repo)
          - name: charts-branch
            value: $(params.charts-branch)
          - name: charts-directory
            value: $(params.charts-directory)
          - name: config-repo
            value: $(params.config-repo)
          - name: config-branch
            value: $(params.config-branch)
          - name: config-directory
            value: $(params.config-directory)
          - name: image-url
            value: $(params.image-url)
          - name: cluster-name
            value: $(params.cluster-name)
          - name: cluster-namespace
            value: $(params.cluster-namespace)
          - name: environment
            value: $(params.environment)
          - name: skip-va
            value: $(params.skip-va)
          - name: skip-deploy
            value: $(params.skip-deploy)
          - name: helm-options
            value: $(params.helm-options)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: blade-ubi-binding-dev
spec:
  params:
    - name: source-repo
      value: "https://github.ibm.com/org-ids/blade-pipeline-broker.git"
    - name: source-branch
      value: "master"
    - name: source-directory
      value: "blade-pipeline-broker"
    - name: charts-repo
      value: "https://github.ibm.com/org-ids/cd-pipeline-kubernetes.git"
    - name: charts-branch
      value: "master"
    - name: charts-directory
      value: "blade-pipeline-broker/cd-pipeline-kubernetes"
    - name: config-repo
      value: "https://github.ibm.com/ids-env/devops-config.git"
    - name: config-branch
      value: "master"
    - name: config-directory
      value: "blade-pipeline-broker/devops-config"
    - name: image-url
      value: "us.icr.io/opentoolchain/blade-pipeline-broker"
    - name: environment
      value: "development"
    - name: cluster-name
      value: otc-us-south-dev
    - name: cluster-namespace
      value: opentoolchain
    - name: skip-va
      value: "false"
    - name: skip-deploy
      value: "false"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: blade-ubi-dev
spec:
  triggers:
    - binding:
        name: blade-ubi-binding-dev
      template:
        name: blade-ubi-trigger-dev
