apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: blade-pipeline-broker-trigger-pii
spec:
  params:
    - name: source-repo
    - name: source-branch
    - name: source-directory
    - name: pii-repo
    - name: pii-branch
    - name: pii-directory

    # CD integration
    - name: api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: api-key
      description: the ibmcloud api key
    - name: toolchain-region
      description: the ibmcloud region containing the toolchain referencing the repository
      default: us-south
    - name: resource-group
      description: the ibmcloud resource group containing the toolchain referencing the repository
      default: default
    - name: toolchain-id
      description: The IBM Cloud Kubernetes cluster region

  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        API: $(params.api)
        REGION: $(params.toolchain-region)
        RESOURCE_GROUP: $(params.resource-group)
        TOOLCHAIN_ID: $(params.toolchain-id)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY_1416501)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: $(params.source-branch)-blade-pii-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(params.source-branch)-blade-pii-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "blade-pipeline-broker-trigger-pii"
      spec:
        pipelineRef:
          name: pipeline-pii
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: $(params.source-branch)-blade-pii-$(uid)-pvc
        serviceAccountName: docker-build-sa
        params:
          - name: source-repo
            value: $(params.source-repo)
          - name: source-branch
            value: $(params.source-branch)
          - name: source-directory
            value: $(params.source-directory)
          - name: pii-repo
            value: $(params.pii-repo)
          - name: pii-branch
            value: $(params.pii-branch)
          - name: pii-directory
            value: $(params.pii-directory)
          - name: environment
            value: $(params.environment)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: blade-pipeline-broker-binding-pii
spec:
  params:
    - name: source-repo
      value: "https://github.ibm.com/org-ids/blade-pipeline-broker.git"
    - name: source-branch
      value: "master"
    - name: source-directory
      value: "blade-pipeline-broker"
    - name: pii-repo
      value: "https://github.ibm.com/org-ids/pii.git"
    - name: pii-branch
      value: "master"
    - name: pii-directory
      value: "blade-pipeline-broker/pii"
    - name: environment
      value: "development"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: blade-pipeline-broker-pii
spec:
  triggers:
    - binding:
        name: blade-pipeline-broker-binding-pii
      template:
        name: blade-pipeline-broker-trigger-pii
