apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: blade-dedicated-trigger-asoc
spec:
  params:
    - name: source-repo
    - name: source-branch
    - name: source-directory
    - name: componen-docker-image
    - name: component-name
    - name: branch-name
    # CD integration
    - name: api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: api-key
      description: the ibmcloud api key
    - name: toolchain-region
      description: the ibmcloud region containing the toolchain referencing the repository
      default: us-south
    - name: resource-group
      description: the ibmcloud resource group containing the toolchain referencing the repository
      default: default
    - name: toolchain-id
      description: The IBM Cloud Kubernetes cluster region
  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        APPSCAN_NAME: $(params.APPSCAN_NAME)
        APPSCAN_APP_ID: $(params.APPSCAN_APP_ID)
        APPSCAN_APP_KEY_ID: $(params.APPSCAN_APP_KEY_ID)
        API: $(params.api)
        REGION: $(params.toolchain-region)
        RESOURCE_GROUP: $(params.resource-group)
        TOOLCHAIN_ID: $(params.toolchain-id)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        APPSCAN_API_KEY_SECRET: $(params.APPSCAN_API_KEY_SECRET)
        API_KEY: $(params.API_KEY_1416501)
        SLACK_WEBHOOK: $(params.SLACK_WEBHOOK)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: $(params.branch-name)-asoc-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        #generateName: $(params.source-branch)-base-run
        name: $(params.branch-name)-asoc-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "blade-dedicated-trigger-asoc"
      spec:
        pipelineRef:
          name: pipeline-asoc
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: $(params.branch-name)-asoc-$(uid)-pvc
        serviceAccountName: docker-build-sa
        params:
          - name: source-repo
            value: $(params.source-repo)
          - name: source-branch
            value: $(params.source-branch)
          - name: source-directory
            value: $(params.source-directory)
          - name: componen-docker-image
            value: $(params.componen-docker-image)
          - name: component-name
            value: $(params.component-name)
          - name: branch-name
            value: $(params.branch-name)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: blade-pipeline-broker-dedicated-binding-asoc
spec:
  params:
    - name: source-repo
      value: "https://github.ibm.com/org-ids/otc-deploy.git"
    - name: source-branch
      value: "master"
    - name: source-directory
      value: "otc-deploy"
    - name: componen-docker-image
      value: "us.icr.io/opentoolchain/blade-pipeline-broker-dedicated:latest"
    - name: component-name
      value: "blade-pipeline-broker"
    - name: branch-name
      value: "dedicated"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: blade-pipeline-broker-dedicated-asoc
spec:
  triggers:
    - binding:
        name: blade-pipeline-broker-dedicated-binding-asoc
      template:
        name: blade-dedicated-trigger-asoc
