apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-managed-worker-staging
spec:
  triggers:
    - bindings:
        - name: region
          value: "us-south"
        - name: environment
          value: "staging"
        - name: clusterName1
          value: otc-tektonpw-dal10-stage
        - name: skipDeploy1
          value: "false"
        - name: clusterName2
          value: otc-tektonpw-dal12-stage
        - name: skipDeploy2
          value: "false"
        - name: clusterName3
          value: otc-tektonpw-dal13-stage
        - name: skipDeploy3
          value: "false"
      template:
        name: tekton-managed-trigger-template
