apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-managed-worker-ca-tor
spec:
  triggers:
    - bindings:
        - name: region
          value: "ca-tor"
        - name: environment
          value: "prod-ca-tor"
        - name: clusterName1
          value: otc-tektonpw-tor01-prod
        - name: skipDeploy1
          value: "false"
        - name: clusterName2
          value: otc-tektonpw-tor04-prod
        - name: skipDeploy2
          value: "false"
        - name: clusterName3
          value: otc-tektonpw-tor05-prod
        - name: skipDeploy3
          value: "false"
        - name: clusterName4
        - name: skipDeploy4
      template:
        name: tekton-managed-trigger-template
