apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-managed-worker-eu-de
spec:
  triggers:
    - bindings:
        - name: region
          value: "eu-de"
        - name: environment
          value: "prod-eu-de"
        - name: clusterName1
          value: otc-tektonpw-fra02-prod
        - name: skipDeploy1
          value: "false"
        - name: clusterName2
          value: otc-tektonpw-fra04-prod
        - name: skipDeploy2
          value: "false"
        - name: clusterName3
          value: otc-tektonpw-fra05-prod
        - name: skipDeploy3
          value: "false"
        - name: clusterName4
          value: ""
        - name: skipDeploy4
          value: "true"
      template:
        name: tekton-managed-trigger-template
