apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-managed-worker-au-syd
spec:
  triggers:
    - bindings:
        - name: region
          value: "au-syd"
        - name: environment
          value: "prod-au-syd"
        - name: clusterName1
          value: otc-tektonpw-syd01-prod
        - name: skipDeploy1
          value: "false"
        - name: clusterName2
          value: otc-tektonpw-syd04-prod
        - name: skipDeploy2
          value: "false"
        - name: clusterName3
          value: otc-tektonpw-syd05-prod
        - name: skipDeploy3
          value: "false"
        - name: clusterName4
          value: ""
        - name: skipDeploy4
          value: "true"
      template:
        name: tekton-managed-trigger-template
