apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-open-cie
spec:
  params:
    # SN - OPEN CIE params
    - name: sn-region
    - name: sn-url
    - name: sn-token
    - name: cr-priority
    - name: cr-type
    - name: cr-description
    - name: cr-purpose
    - name: cr-close-notes
    - name: cr-close-category
  workspaces:
    - name: pipeline-pvc
  tasks:
    - name: open-cie
      taskRef:
        name: open-cie
      params:
        - name: sn-region
          value: $(params.sn-region)
        - name: sn-url
          value: $(params.sn-url)
        - name: sn-token
          value: $(params.sn-token)
        - name: cr-priority
          value: $(params.cr-priority)
        - name: cr-type
          value: $(params.cr-type)
        - name: cr-description
          value: $(params.cr-description)
        - name: cr-purpose
          value: $(params.cr-purpose)
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
