apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: open-cie
spec:
  description: >-
    This task opens a CIE in ServiceNow and returns a Incident ID.
  params:
    - name: param1
      default: 'development'
  results:
    - name: incident_id
      description: the incident id that was created by the task
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
  - name: open-cie
    image: us.icr.io/opentoolchain/cd-deploy-base:deploy
    imagePullPolicy: IfNotPresent
    env:
      - name: SN_REGION
        value: $(params.param1)
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        echo "Pipeline Running"
