apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-open-cie
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipeline-open-cie-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: instana-deploy-$(uid)
      spec:
        pipelineRef:
          name: pipeline-open-cie
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: instana-deploy-$(uid)-pvc
        params:
          # SN params
          - name: param1
            value: $(params.param1)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: crypto-open-cie-binding
spec:
  params:
    - name: param1
      value: ""
    template:
      name: trigger-open-cie
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: crypto-open-cie-listener
spec:
  triggers:
    - bindings:
        name: crypto-open-cie-binding
      template:
        name: trigger-open-cie
