apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-open-cie
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipeline-open-cie-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: instana-deploy-$(uid)
      spec:
        pipelineRef:
          name: pipeline-open-cie
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: instana-deploy-$(uid)-pvc
        params:
          # SN params
          - name: sn-region
            value: $(params.sn-region)
          - name: sn-url
            value: $(params.sn-url)
          - name: sn-token
            value: $(params.sn-token)
          - name: cr-priority
            value: $(params.cr-priority)
          - name: cr-type
            value: $(params.cr-type)
          - name: cr-description
            value: $(params.cr-description)
          - name: cr-purpose
            value: $(params.cr-purpose)
          - name: cr-close-notes
            value: $(params.cr-close-notes)
          - name: cr-close-category
            value: $(params.cr-close-category)
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: crypto-open-cie-listener
spec:
  triggers:
    - bindings:
        - params:
            - name: cr-type
              value: ""
            - name: cr-priority
              value: ""
            - name: cr-description
              value: "Template cr description"
            - name: cr-purpose
              value: "Template cr purpose"
            - name: cr-close-notes
              value: "Templage ct close notes:"
            - name: cr-close-category
              value: "successful"
      template:
        name: trigger-open-cie
