apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pgbouncer-pipeline
spec:
  params:
    - name: pipeline-pvc
    - name: source_repo
    - name: source_branch
    - name: script_repo
    - name: script_branch
    - name: script_directory
    - name: config_repo
    - name: config_branch
    - name: config_directory
    - name: environment
    - name: chartNamespace
    - name: clusterName1
    - name: skipDeploy1
    - name: clusterName2
    - name: skipDeploy2
    - name: clusterName3
    - name: skipDeploy3
    - name: helmVersion

  tasks:
    - name: clone-source-repo
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
    - name: clone-script-repo
      runAfter: [clone-source-repo]
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.script_repo)
        - name: branch
          value: $(params.script_branch)
        - name: directoryName
          value: $(params.script_directory)
    - name: clone-config-repo
      runAfter: [clone-script-repo]
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.config_repo)
        - name: branch
          value: $(params.config_branch)
        - name: directoryName
          value: $(params.config_directory)
    - name: deploy-cluster-1
      runAfter: [clone-config-repo]
      taskRef:
        name:  deploy-pgbouncer
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: environment
          value: $(params.environment)
        - name: skipDeploy
          value: $(params.skipDeploy1)
        - name: clusterName
          value: $(params.clusterName1)
        - name: chartNamespace
          value: $(params.chartNamespace)
        - name: helmVersion
          value: $(params.helmVersion)
        - name: script_directory
          value: $(params.script_directory)
    - name: deploy-cluster-2
      runAfter: [deploy-cluster-1]
      taskRef:
        name:  deploy-pgbouncer
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: environment
          value: $(params.environment)
        - name: skipDeploy
          value: $(params.skipDeploy2)
        - name: clusterName
          value: $(params.clusterName2)
        - name: chartNamespace
          value: $(params.chartNamespace)
        - name: helmVersion
          value: $(params.helmVersion)
        - name: script_directory
          value: $(params.script_directory)
    - name: deploy-cluster-3
      runAfter: [deploy-cluster-2]
      taskRef:
        name:  deploy-pgbouncer
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: environment
          value: $(params.environment)
        - name: skipDeploy
          value: $(params.skipDeploy3)
        - name: clusterName
          value: $(params.clusterName3)
        - name: chartNamespace
          value: $(params.chartNamespace)
        - name: helmVersion
          value: $(params.helmVersion)
        - name: script_directory
          value: $(params.script_directory)