apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-add-preprod-ctask
spec:
  params:
    - name: snUrl
    - name: e2eBuildId
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: add-preprod-ctask
      taskRef:
        name:  add-preprod-ctask
      params:
        - name: snUrl
          value: $(params.snUrl)
        - name: e2eBuildId
          value: $(params.e2eBuildId)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc

