apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-base-pipeline
spec:
  params:
    - name: imageName
      description: the name of the output docker image
    - name: imageTag
      description: the tag for the output docker image
    - name: accountApiKey1416501
      description: api key
    - name: accountApiKey1308775
      description: api key for docker build machine
    - name: crRegion
      description: the CR region to use
    - name: crAccountName
      description: the CR account name to use
    - name: idsToken
      description: the ids token to use to clone repos
    - name: registryUrl
      description: the CR registry URL to use
    - name: registryNamespace
      description: the CR NS to use 
    - name: charts_repo
      description: The charts repo url
    - name: config_repo
      description: The config repo url    
  tasks:
  - name: build-base-image
    taskRef:
      name:  build-base
    params:
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: idsToken
        value: $(params.idsToken)
      - name: imageName
        value: cd-deploy-base
      - name: imageTag
        value: deploy
      - name: charts_repo
        value: $(params.charts_repo)
      - name: config_repo
        value: $(params.config_repo)
  - name: nodejs10
    taskRef:
      name: build-base
    params:
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: idsToken
        value: $(params.idsToken)
      - name: imageName
        value: cd-build-base
      - name: imageTag
        value: nodejs10.build
      - name: charts_repo
        value: $(params.charts_repo)
      - name: config_repo
        value: $(params.config_repo)
  - name: java
    taskRef:
      name: build-base
    params:
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: idsToken
        value: $(params.idsToken)
      - name: imageName
        value: cd-build-base
      - name: imageTag
        value: java.build
      - name: charts_repo
        value: $(params.charts_repo)
      - name: config_repo
        value: $(params.config_repo)
  - name: go 
    taskRef:
      name: build-base
    params:
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: idsToken
        value: $(params.idsToken)
      - name: imageName
        value: cd-build-base
      - name: imageTag
        value: go1.10.build
      - name: charts_repo
        value: $(params.charts_repo)
      - name: config_repo
        value: $(params.config_repo)
  - name: nodejs10-run 
    runAfter: [nodejs10]
    taskRef:
      name: run-base
    params:
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: idsToken
        value: $(params.idsToken)
      - name: imageName
        value: cd-build-base
      - name: imageTag
        value: go1.10.build
      - name: charts_repo
        value: $(params.charts_repo)
      - name: config_repo
        value: $(params.config_repo)
  - name: websphere-liberty-run
    runAfter: [java]
    taskRef:
      name: run-base
    params:
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: idsToken
        value: $(params.idsToken)
      - name: imageName
        value: cd-build-base
      - name: imageTag
        value: go1.10.build
      - name: charts_repo
        value: $(params.charts_repo)
      - name: config_repo
        value: $(params.config_repo)