apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
    - name: vault
      port: 8200
  selector:
    app: vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  conf.hcl: |-
    listener "tcp" {
        address = "0.0.0.0:8200"
        tls_cert_file = "/vault/config/cert.pem"
        tls_key_file = "/vault/config/cert.key"
    }

    backend "inmem" {
    }

  cert.pem: |-
    -----BEGIN CERTIFICATE-----
    MIID0jCCArqgAwIBAgIUabUAeSAlNDmNDBc+2EQMwo6UckwwDQYJKoZIhvcNAQEL
    BQAwGjEYMBYGA1UEAxMPSW50ZXJtZWRpYXRlIENBMCAXDTE3MDMwMzA1NDgxMVoY
    DzIwNjcwMjE5MDM0ODQxWjAQMQ4wDAYDVQQDEwV2YXVsdDCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAKgBs/FzWhP5D/HYWtnZlL3dUndtE1B2Jgg2dG+u
    1wZgXEZ8YhctwvzVAlFX3Xrz4vRhZlkOfE+Y7GbFgXsPMCXqDh7sd/+g6Vnutjqh
    +9yhyy6Hq+DaSuD399RBG81GBsF2+LCVg+R3mC8pMXMYPJ+Gj+p++O0NN+bYPcGA
    q8gJ40CiLHc39j6RkA/BCiVz/7+jLy+VAbRfft8PsCEiDjFOSgmvnxRDDgKrB9mP
    KX7/hyWFTaBxr1ihS+vPz8VeSmaIa1ddPt7SC72JGMzF4Stt1ef5/miHY7gqcDBm
    qoIkrmef2KzJ3L4su3JAETcbPL16BFJDHR2cB2V8qSELG1cCAwEAAaOCARYwggES
    MA4GA1UdDwEB/wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    HQYDVR0OBBYEFH27PKp9+llnntdiSV9lVpACIvOwMB8GA1UdIwQYMBaAFL90TV74
    j38QE0cSGrmn2PUUX75qMEMGCCsGAQUFBwEBBDcwNTAzBggrBgEFBQcwAoYnaHR0
    cDovL3ZhdWx0OjgyMDAvdjEvaW50ZXJtZWRpYXRlLWNhL2NhMCEGA1UdEQQaMBiC
    BXZhdWx0gglsb2NhbGhvc3SHBH8AAAEwOQYDVR0fBDIwMDAuoCygKoYoaHR0cDov
    L3ZhdWx0OjgyMDAvdjEvaW50ZXJtZWRpYXRlLWNhL2NybDANBgkqhkiG9w0BAQsF
    AAOCAQEAaUcQsr/fIZJ1GWW3WnfLJ4b3P+YHIP/cer5Mcv7Y5pqnozr7gT5zyGSR
    0qNv5w1ZrN0qglxz3UBI/w6UrQJLPGt8Hm5+5y0YRIcLqKji3XqWE1guwyeMgCRt
    SiZQzP1VaF+vHcw6qcn6Ge/vfFbzeq67/i5ueZTopy+uuz2wjPF16jkxVjPQDeop
    TnjUTFpWHeRG+GBLleEJRkZRVJ1k/mZm5kCk+8kyfGggNgB84fmL9UBGxAH7Dn+Z
    Pur/BMTEpdAdXmAk91Ux/Av2/0LV8ozp5hGBttLRkgEqeeBflNeDZxSeLSwhhHYL
    iTmTd3zTZltx7X7bGJ9YUZvNTYE9Vw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIUXvxwgZK/6qtpxmuZty23U6AVnF0wDQYJKoZIhvcNAQEL
    BQAwEjEQMA4GA1UEAxMHUm9vdCBDQTAgFw0xNzAzMDMwNTQ2NDRaGA8yMDY3MDIx
    OTA0NDcxNFowGjEYMBYGA1UEAxMPSW50ZXJtZWRpYXRlIENBMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAol8fFnbOHydXo6wnuuhEb3NfJu0+0RTgFzWr
    6xekvQrsRL4tUIonhC3xOXyINswhOI53XLZCTnSd4L7oVdY0umoNRXqtpSvjulK0
    Ggd5+dxzBKQbAQ+DWemN8g9fLbkd8R0fx3gtmjY+4hASFuyX+wI/jroTy+Cyluid
    ahVZmzDEW/KyGjBN4xxkTlHceX8VFvwb7f/39ALCl9mBLpDiTD8qLkZRPZUzX02J
    OGLylGK57UTS/9zLC39+eil1/qycpBPHbVXj+AnSIp4F+ikAfY1OWC08fqK1H6LA
    iuqk2uSA4Ft0vyRhGPt/TttrvWTVx+VeCxHi+cXmtY9lQnuaqwIDAQABo4HUMIHR
    MA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS/dE1e
    +I9/EBNHEhq5p9j1FF++ajAfBgNVHSMEGDAWgBSp7Khi3m9qqsC82CRLaPkPcYO2
    nzA7BggrBgEFBQcBAQQvMC0wKwYIKwYBBQUHMAKGH2h0dHA6Ly92YXVsdDo4MjAw
    L3YxL3Jvb3QtY2EvY2EwMQYDVR0fBCowKDAmoCSgIoYgaHR0cDovL3ZhdWx0Ojgy
    MDAvdjEvcm9vdC1jYS9jcmwwDQYJKoZIhvcNAQELBQADggEBABMF+ferbsJC3dlw
    6kUsd+idLuYM1eXhpjgkgh2D/5H01Hjar39tuIZNH8uTPCNNvV/o5UHEG7b97XEk
    +EXH9HZopFYYuSqQZqE+x8Cq9uKXWaSI69w7N9zVyMFEX+ZsHRm6lvntedZhXERU
    HHUiD8Qvf5Dui4RLXcO6eKT6zr0fVNurl6hs3l6ma4Z0zDmrgBhlxrW98gXhRRyK
    5M0AxBAfNRsT7hu+Tp7xrNuhDOE+SPotbIVi30rVAn88BhkYAtJK3CIAKRJ1W5bW
    Sjv5ZzZvfE6u0R255qpoJQfUjHUL1OmFTW3yJrgjabrz/GgsagbD53h33ML9cNez
    hhBu79U=
    -----END CERTIFICATE-----

  cert.key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAqAGz8XNaE/kP8dha2dmUvd1Sd20TUHYmCDZ0b67XBmBcRnxi
    Fy3C/NUCUVfdevPi9GFmWQ58T5jsZsWBew8wJeoOHux3/6DpWe62OqH73KHLLoer
    4NpK4Pf31EEbzUYGwXb4sJWD5HeYLykxcxg8n4aP6n747Q035tg9wYCryAnjQKIs
    dzf2PpGQD8EKJXP/v6MvL5UBtF9+3w+wISIOMU5KCa+fFEMOAqsH2Y8pfv+HJYVN
    oHGvWKFL68/PxV5KZohrV10+3tILvYkYzMXhK23V5/n+aIdjuCpwMGaqgiSuZ5/Y
    rMncviy7ckARNxs8vXoEUkMdHZwHZXypIQsbVwIDAQABAoIBAFACt5qWj+CRLZnE
    qsezClY9j+eWR6t7CPPCU0NY5ciAnZFn7SMSxRi5rOfmS3EhswUlWaOx9VvG/VaY
    WuirPAfiZqUtgpx4Gomc2KYlvJe/ac8YB7AG5cAr95fbBg2FevQp35fhLLXiitRy
    7rzcXwqt/93yaEQklmnWs9pyl9ykq0PKiMJMj/XuotFE6Bd29Ojpi2GPCQmK9ofo
    iycMCZRl8zpxZ46wQHfovT++jotk/tzqIZ7WJyt4GylB+syapdxmdLRhpdYQ5z3N
    +k8xnsY87y8cUMYExLSB1VDLBTKb5nHbf4u99AHxcM47iXF8Bbw6tOAOWDjy0Udx
    pTcxmjkCgYEA0/lxdKZ42FWhA9nP8HD0HFwlhcQR73S/Z9aC32d9zUkyjSehLnXm
    mhhKPfJtsIERNdWXZDT5vl+JwfIkHrRwPCESlsQrkB0cP4ywfRjyuLxnbbf74ocA
    VR5qYp2hycdFCUYhM/q/hsHEwy/DA9jchtY3PDQt1XGFkCqJWvJ3ZQUCgYEAyuaF
    OJ3TDelYSI83mpeLlvpJBpBP4FEYmtYQjyS4YohCyJWbOzaMCF3Sppzk1t3t+JTH
    ahBePl9WuUyYGJcIZcOh9zsTFiXxkJZpoYqApuOD/OsSxXOF3razHpquc/irICyw
    89pwxHiPSP88TFhA5hTLyn+EBB2+7frocLLB7asCgYAg7SpWeFVlJUfxlS/bpXAF
    x7p8YMx4aaYhtwx1L1o3PRuBGZrL4LyFSyidHr8zH5lQx3DQu/nfPG/llHtP2a9l
    Z62/hZFOvXbZ2DzB8dIiKAHY5S9XLKk8j5Du6JVtBmsO2bnmnRiLEiZCO3ULb/Ax
    caz6yRAli5C3qCPV4LvzEQKBgD6icMeseMWXnggwJeMUGyRNORPMosvFXQoXQN9f
    X4gTNkKDZHsf+JRwmiGS11W5Bsgw7WpBiUZJ2hSzn1Qf85iujqYqV1cD+ZE/zXXv
    so1SOKFv08ieQ9ofniW5bFcikXkKMsnkSeFssha/q9aJe+dKzipBuPgoUpNWXEDF
    /fWnAoGAYGh0fZ9pZOnp3glvVqWAcAABbARm5x3O8dwq40ZRfPvxJn0S3TIsZW2w
    epV4v3ZP260J81Dbxceg6ZGSGBtbHjEWXj4PzKbDaqlIKV5seme7VQO476KZtpdQ
    eT3jPxyrm58zSuXiwmKzrwiqyJ0Fz/Z81qEaLlw0yv9Tlv944dc=
    -----END RSA PRIVATE KEY-----
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault
        command:
          - vault
          - server
          - -config=/vault/config/
        name: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /vault/config
        securityContext:
         capabilities:
           add:
             - IPC_LOCK
      volumes:
        - name: config-volume
          configMap:
            name: vault