##########################################################################################
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2020, 2021. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
##########################################################################################
FROM alpine:3.13.2

RUN apk update && apk upgrade


