###############################################################################
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2020. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
###############################################################################
#FROM registry.access.redhat.com/ubi8/nodejs-12:latest
FROM registry.access.redhat.com/ubi8:latest

USER root

RUN yum update -y && \
    yum install hostname -y && \
    yum remove -y mariadb-connector-c && \
    yum clean all -y