FROM us.icr.io/opentoolchain/travis-worker:run

USER root

RUN yum update -y && \
    yum clean all -y

COPY ./docker_ubi/entrypoint.sh /root/entrypoint.sh
COPY ./docker_ubi/dockerpullstart.sh /root/dockerpullstart.sh

ENTRYPOINT ["/root/entrypoint.sh"]
CMD ["/usr/bin/dockerd"]