FROM golang:1.9-alpine as builder

ADD go $GOPATH

WORKDIR $GOPATH/src/github.ibm.com/continuous-delivery/yamltoenv

RUN apk --update add gcc git musl-dev \
 && go get -u github.com/golang/dep/cmd/dep \
 && dep ensure \
 && go build -o yamltoenv yamltoenv.go 

FROM alpine:latest

COPY --from=builder /go/src/github.ibm.com/continuous-delivery/yamltoenv/yamltoenv /yamltoenv 

ENTRYPOINT ["/yamltoenv"]
