#ServiceNow
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: servicenow
spec:
  params:
    - name: cr-type
      value: ""
    - name: cr-priority
      value: ""
    - name: cr-description
      value: "Template cr description"
    - name: cr-purpose
      value: "Template cr purpose"
    - name: cr-close-notes
      value: "Templage ct close notes:"
    - name: cr-close-category
      value: "successful"
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: test-servicenow
spec:
  params:
    - name: sn-url
      value: https://watsontest.service-now.com
    - name: sn-token
      value: $(params.TEST_SN_TOKEN)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: prod-servicenow
spec:
  params:
    - name: sn-url
      value: https://watson.service-now.com
    - name: sn-token
      value: $(params.PROD_SN_TOKEN)
