# Documentation on available configuration
# https://pages.github.ibm.com/one-pipeline/docs/custom-scripts.html

version: '1'

setup:
  image: us.icr.io/otc-ops/otc-deploy:test
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./tekton/one-pipeline/cd/setup.sh

deploy:
  #image: ibmcom/pipeline-base-image:2.6
  image: us.icr.io/opentoolchain/cd-deploy-base:deploy
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./tekton/one-pipeline/cd/deploy.sh

acceptance-test:
  image: us.icr.io/otc-ops/otc-deploy:test
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./tekton/one-pipeline/cd/acceptance_test.sh
