development:
  basedomain: devops.dev.us-south.bluemix.net
  vault:
    secretPaths:
    - generic/project/continuous-delivery-dev/cd-pipeline
  configmap:
    data:
      AMQPS_PORT: 18815
      AMQP_HOST: portal1532-1.otc-pipeline-ys1-dev-2017-01-23.ibm-16.composedb.com
      AMQP_PATH: /otc-pipeline-ys1-dev-2017-01-23
      AMQP_PREFETCH: 1
      AMQP_PROTOCOL: amqps
      AMQP_REJECT_UNAUTH_CERTS: true
      AMQP_SSL_PROTOCOL: TLSv1_2_method
      AMQP_USER: jazzhub
      ARCHIVE_QUEUE_NAME: reporting.archive
      ARCHIVE_TYPE: s3ObjectStorage
      CERT_FILE: keys/server.crt
      CF_DOMAIN: stage1.ng.bluemix.net
      CF_INSTANCES: 3
      CF_MEMORY: 1G
      CONTEXT_PATH: /api
      DB_HOST: sl-us-dal-9-portal.1.dblayer.com
      DB_NAME: compose
      DB_PORT: 10570
      DB_SSL_PROTOCOL: TLSv1.2
      DB_TYPE: postgresql
      DB_USER: admin
      KEY_FILE: keys/server.key
      LOGICAL_APP_NAME: pipeline-log-service
      LOGICAL_ENV_NAME: DEV
      LOGNAME: pipeline
      LOGS_EXCHANGE_NAME: reporting
      LOGS_QUEUE_MSG_TTL: 7200000
      LOGS_QUEUE_NAME: reporting.jobs.logs
      LOGS_ROUTING_KEY: reporting.jobs.logs
      NEW_RELIC_APP_NAME: Pipeline Log Service - YS1
      OBJECT_STORAGE_INTERFACE: public
      OBJECT_STORAGE_PROJECT: object_storage_6057de4d_a7c7_4b4a_93be_940ca5764c53
      OBJECT_STORAGE_PROJECT_ID: 1d644021a18b420882d129127edd575c
      OBJECT_STORAGE_REGION: dallas
      OBJECT_STORAGE_URL: https://identity.open.softlayer.com
      OBJECT_STORAGE_USERNAME: 247af93fbd3a4004acf76213301b363f
      OLD_ARCHIVE_TYPE: objectstorage
      S3_LOGS_BUCKET_NAME: pipeline-logs-ys1-dev
      S3_STORAGE_ENDPOINT: https://s3-api.us-geo.objectstorage.softlayer.net
      S3_STORAGE_REGION: us-standard
      SECGRP: GRP3DEVS
      VM_AMQPS_PORT: 5674
      VM_AMQP_HOST: 169.55.35.183
      VM_AMQP_USER: guest
      log4js_logmet_component: otc-pipeline-log-service
      log4js_logmet_enabled: true
      log4js_logmet_logging_host: ingest.logging.stage1.ng.bluemix.net
      log4js_logmet_logging_port: 9091
      log4js_logmet_space_id: ed841776-9394-4b51-a86c-72ddc5529e05
      log4js_syslog_appender_enabled: true
      log4js_syslog_appender_host: syslog.prd.ccs.ibmcloud.com
      log4js_syslog_appender_port: 6515
      log4js_syslog_appender_product: otc-pipeline-log-service-ys1-dev
      log4js_syslog_appender_url: devops.stage1.ng.bluemix.net
      log4js_syslog_appender_whitelist: audit-logs
