apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-restarter
spec:
  params:
    - name: environment
    - name: serviceName
    - name: clusterName1
    - name: skipDeploy1
    - name: clusterName2
    - name: skipDeploy2
    - name: clusterName3
    - name: skipDeploy3
    - name: clusterNamespace
      default: 'opentoolchain'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: restart-cluster-1
      taskRef:
        name:  restart-deployment
      params:
        - name: environment
          value: $(params.environment)
        - name: serviceName
          value: $(params.serviceName)
        - name: skipDeploy
          value: $(params.skipDeploy1)
        - name: clusterName
          value: $(params.clusterName1)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: restart-cluster-2
      runAfter: [restart-cluster-1]
      taskRef:
        name:  restart-deployment
      params:
        - name: environment
          value: $(params.environment)
        - name: serviceName
          value: $(params.serviceName)
        - name: skipDeploy
          value: $(params.skipDeploy2)
        - name: clusterName
          value: $(params.clusterName2)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: restart-cluster-3
      runAfter: [restart-cluster-2]
      taskRef:
        name:  restart-deployment
      params:
        - name: environment
          value: $(params.environment)
        - name: serviceName
          value: $(params.serviceName)
        - name: skipDeploy
          value: $(params.skipDeploy3)
        - name: clusterName
          value: $(params.clusterName3)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

