apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: restart-au-syd-trigger-dev
spec:
  params:
    - name: environment
    - name: serviceName
    - name: clusterNamespace
    - name: clusterName1
    - name: skipDeploy1
    - name: clusterName2
    - name: skipDeploy2
    - name: clusterName3
    - name: skipDeploy3

    # CD integration
    - name: api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: apikey
      description: the ibmcloud api key
    - name: toolchainRegion
      description: the ibmcloud region containing the toolchain referencing the repository
      default: us-south
    - name: resourceGroup
      description: the ibmcloud resource group containing the toolchain referencing the repository
      default: default
    - name: toolchainId
      description: The IBM Cloud Kubernetes cluster region

  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        API: $(params.api)
        REGION: $(params.toolchainRegion)
        RESOURCE_GROUP: $(params.resourceGroup)
        TOOLCHAIN_ID: $(params.toolchainId)
        IDS_USER: $(params.IDS_USER)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY_1416501)
        API_KEY_1308775: $(params.API_KEY_1308775)
        API_KEY_1651315: $(params.API_KEY_1651315)
        DEPLOY_API_KEY: $(params.API_KEY_1416501)
        REGISTRY_API_KEY: $(params.API_KEY_1416501)
        IDS_TOKEN: $(params.IDS_TOKEN)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: $(params.charts_branch)-restart-au-syd-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce

    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        #generateName: $(params.source_branch)-base-run
        name: $(params.charts_branch)-restart-au-syd-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "restart-au-syd-trigger-dev"
      spec:
        pipelineRef:
          name: pipeline-restarter
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: $(params.charts_branch)-restart-au-syd-$(uid)-pvc
        serviceAccountName: docker-build-sa
        params:
          - name: clusterNamespace
            value: $(params.clusterNamespace)
          - name: environment
            value: $(params.environment)
          - name: serviceName
            value: $(params.serviceName)
          - name: clusterName1
            value: $(params.clusterName1)
          - name: skipDeploy1
            value: $(params.skipDeploy1)
          - name: clusterName2
            value: $(params.clusterName2)
          - name: skipDeploy2
            value: $(params.skipDeploy2)
          - name: clusterName3
            value: $(params.clusterName3)
          - name: skipDeploy3
            value: $(params.skipDeploy3)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: restart-au-syd-binding-dev
spec:
  params:
    - name: environment
      value: "au-syd"
    - name: serviceName
      value: "pipeline-service"
    - name: clusterNamespace
      value: opentoolchain
    - name: clusterName1
      value: otc-syd01-prod
    - name: skipDeploy1
      value: "false"
    - name: clusterName2
      value: otc-au-syd-prod
    - name: skipDeploy2
      value: "false"
    - name: clusterName3
      value: 'none'
    - name: skipDeploy3
      value: "true"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: restart-au-syd-dev
spec:
  triggers:
    - binding:
        name: restart-au-syd-binding-dev
      template:
        name: restart-au-syd-trigger-dev
