  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cd-config
  data:
    # original config map values
    API: "https://cloud.ibm.com"
    REGION: "us-south"
    RESOURCE_GROUP: "f778a8021f114465aff0e39885cff51a"
    TOOLCHAIN_ID: "c028c8ce-f20a-407d-9a4b-28ddca46e701"
    IDS_USER: "idsorg"
