  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cd-config
  data:
    SOURCE_BRANCH:  "master"
    CHARTS_REPO: "https://github.ibm.com/org-ids/cd-pipeline-kubernetes.git"
    CHARTS_BRANCH: "master"
    CONFIG_REPO: "https://github.ibm.com/ids-env/devops-config.git"
    CONFIG_BRANCH: "master"
    ENVIRONMENT: "development"
    CLUSTERNAME: "otc-us-south-dev"
    CLUSTERNAMESPACE: "opentoolchain"
    SKIPBUILD: "false"
    SKIPVA: "true"
    SKIPDEPLOY: "false"
    # original config map values
    API: "https://cloud.ibm.com"
    REGION: "us-south"
    RESOURCE_GROUP: "f778a8021f114465aff0e39885cff51a"
    TOOLCHAIN_ID: "c028c8ce-f20a-407d-9a4b-28ddca46e701"
    IDS_USER: "idsorg"
