apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: rolling-deployments-template
spec:
  params:
    - name: script_repo
    - name: script_branch
    - name: script_directory

    # CD integration
    - name: apikey
      description: the ibmcloud api key
    - name: regions
      description: one of syd,tok,lon,wdc,dal,au-syd,fra
      default: ""
    - name: cluster_region
      description: ibmcloud region for the cluster to rollout
      default: "us-south"

  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        IDS_USER: $(params.IDS_USER)
        REGION: $(params.CLUSTER_REGION)
        ALL_REGIONS: $(params.ALL_REGIONS)

    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY_1416501)
        IDS_TOKEN: $(params.IDS_TOKEN)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name:  rolling-deployments-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: rolling-deployments-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "rolling-deployments-template"
      spec:
        pipelineRef:
          name: pipeline-rolling-deployments
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: rolling-deployments-$(uid)-pvc
        serviceAccountName: docker-build-sa
        params:
          - name: script_repo
            value: $(params.script_repo)
          - name: script_branch
            value: $(params.script_branch)
          - name: script_directory
            value: $(params.script_directory)
          - name: regions
            value: $(params.ALL_REGIONS)
          - name: cluster_region
            value: $(params.CLUSTER_REGION)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: rolling-deployments-binding
spec:
  params:
    - name: script_repo
      value: "https://github.ibm.com/org-ids/cd-pipeline-kubernetes.git"
    - name: script_branch
      value: "master"
    - name: script_directory
      value: "cd-pipeline-kubernetes"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: rolling-deployments
spec:
  triggers:
    - binding:
        name: rolling-deployments-binding
      template:
        name: rolling-deployments-template
