apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-base-ubi-common-tools
spec:
  params:
    - name: source_repo
    - name: source_branch
    - name: source_directory
    - name: image_tag
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directory-name
          value: $(params.source_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: travis-common-tools-secure
      runAfter: [clone-source-repo]
      taskRef:
        name: run-base-image
      params:
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: icr.io/continuous-delivery/pipeline/tekton/common-tools
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs12ubi
        - name: dockerFile
          value: docker/Dockerfile.common_tools_ubi
        - name: imageTag
          value: $(params.image_tag)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: travis-common-tools-secure-va
      runAfter: [travis-common-tools-secure]
      taskRef:
        name: run-va
      params:
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: icr.io/continuous-delivery/pipeline/tekton/common-tools
        - name: runBaseImage
          value: ibmcom/pipeline-base-image:latest
        - name: imageTag
          value: $(params.image_tag)
        - name: registryScope
          value: "global"
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
  