apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-base-ubi-docker
spec:
  params:
    - name: source_repo
    - name: source_branch
    - name: source_directory
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directory-name
          value: $(params.source_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: travis-jq-kubectl-secure
      runAfter: [clone-config-repo]
      taskRef:
        name: run-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: icr.io/continuous-delivery/pipeline/tekton/helm-kubectl-jq
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs12ubi
        - name: dockerFile
          value: docker/Dockerfile.jq_kubectl_ubi
        - name: imageTag
          value: ''
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: travis-jq-kubectl-secure-va
      runAfter: [travis-docker-secure]
      taskRef:
        name: run-va
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: icr.io/continuous-delivery/pipeline/tekton/helm-kubectl-jq
        - name: runBaseImage
          value: ibmcom/pipeline-base-image:latest
        - name: imageTag
          value: ''
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
  