apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-base-ubi-ci
spec:
  params:
    - name: charts_repo
    - name: charts_branch
    - name: charts_directory
    - name: config_repo
    - name: config_branch
    - name: config_directory
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.charts_repo)
        - name: branch
          value: $(params.charts_branch)
        - name: directory-name
          value: $(params.charts_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-config-repo
      runAfter: [clone-source-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.config_repo)
        - name: branch
          value: $(params.config_branch)
        - name: directory-name
          value: $(params.config_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: nodejs12-ubi
      runAfter: [clone-config-repo]
      taskRef:
        name: build-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageName
          value: cd-build-base
        - name: imageTag
          value: nodejs12ubi
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs12ubi
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: nodejs14-ubi
      runAfter: [clone-config-repo]
      taskRef:
        name: build-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageName
          value: cd-build-base
        - name: imageTag
          value: nodejs14ubi
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs14ubi
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: java-ubi
      runAfter: [clone-config-repo]
      taskRef:
        name: build-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageName
          value: cd-build-base
        - name: imageTag
          value: java-ubi
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:java-ubi
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: deploy
      runAfter: [clone-config-repo]
      taskRef:
        name:  build-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageName
          value: cd-deploy-base
        - name: imageTag
          value: onepipeline
        - name: tagSuffix
          value: ''
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs14ubi
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: deploy-va
      runAfter: [deploy]
      taskRef:
        name: run-va
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: us.icr.io/opentoolchain/cd-deploy-base
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs14ubi
        - name: imageTag
          value: onepipeline
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: go
      runAfter: [clone-config-repo]
      taskRef:
        name: build-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageName
          value: cd-build-base
        - name: imageTag
          value: go1.15
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs14ubi
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: nodejs12-ubi-run
      runAfter: [nodejs12-ubi]
      taskRef:
        name: run-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: us.icr.io/opentoolchain/ibmnode
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs12ubi
        - name: dockerFile
          value: docker/Dockerfile.nodejs12ubi.run
        - name: imageTag
          value: 12ubisecure
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: nodejs12-ubi-va
      runAfter: [nodejs12-ubi-run]
      taskRef:
        name: run-va
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: us.icr.io/opentoolchain/ibmnode
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs12ubi
        - name: imageTag
          value: 12ubisecure
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: nodejs14-ubi-run
      runAfter: [nodejs14-ubi]
      taskRef:
        name: run-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: us.icr.io/opentoolchain/ibmnode
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs14ubi
        - name: dockerFile
          value: docker/Dockerfile.nodejs14ubi.run
        - name: imageTag
          value: 14ubisecure
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: nodejs14-ubi-va
      runAfter: [nodejs14-ubi-run]
      taskRef:
        name: run-va
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: us.icr.io/opentoolchain/ibmnode
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs14ubi
        - name: imageTag
          value: 14ubisecure
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: websphere-liberty-ubi-run
      runAfter: [java-ubi]
      taskRef:
        name: run-base
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: us.icr.io/opentoolchain/websphere-liberty-ubi
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:java-ubi
        - name: dockerFile
          value: docker/Dockerfile.java-ubi.run
        - name: imageTag
          value: secure
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: websphere-liberty-ubi-va
      runAfter: [websphere-liberty-ubi-run]
      taskRef:
        name: run-va
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: us.icr.io/opentoolchain/websphere-liberty-ubi
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:java-ubi
        - name: imageTag
          value: secure
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
  
