basedomain: devops.dev.us-south.bluemix.net

image:
  pullPolicy: Always

vault:
  secretPaths:
  - secret/pipeline/development

resources:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

service:
  type: ClusterIP
