basedomain: devops.dev.us-south.bluemix.net

image:
  pullPolicy: IfNotPresent

vault:
  roleID: b6258dfa-f600-cdbc-c3e5-b79604a34a3b
  secretPaths: secret/pipeline/development

resources:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

service:
  type: ClusterIP
