apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-pii
spec:
  params:
    - name: source-repo
    - name: source-branch
    - name: source-directory
    - name: pii-repo
    - name: pii-branch
    - name: pii-directory
    - name: environment
    - name: run-base-image
      default: us.icr.io/opentoolchain/cd-build-base:nodejs12
    - name: java-pattern
      default: 'false'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source-repo)
        - name: branch
          value: $(params.source-branch)
        - name: directory-name
          value: $(params.source-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-pii-repo
      runAfter: [clone-source-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.pii-repo)
        - name: branch
          value: $(params.pii-branch)
        - name: directory-name
          value: $(params.pii-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: pii-drop
      runAfter: [clone-pii-repo]
      taskRef:
        name:  run-pii
      params:
        - name: source-directory
          value: $(params.source-directory)
        - name: run-base-image
          value: $(params.run-base-image)
        - name: java-pattern
          value: $(params.java-pattern)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
