apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-close-cr
spec:
  params:
    - name: charts_repo
    - name: charts_branch
    - name: charts_directory
    - name: environment
    - name: deployClusters
    - name: snUrl
    - name: deployChannel
      default: '#devops-otc-deployment'
    - name: tocChannel
      default: '#devops-cd-cie'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-charts-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.charts_repo)
        - name: branch
          value: $(params.charts_branch)
        - name: directory-name
          value: $(params.charts_directory)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: close-cr
      runAfter: [clone-charts-repo]
      taskRef:
        name:  close-cr
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: environment
          value: $(params.environment)
        - name: deployClusters
          value: $(params.deployClusters)
        - name: snUrl
          value: $(params.snUrl)
        - name: deployChannel
          value: $(params.deployChannel)
        - name: tocChannel
          value: $(params.tocChannel)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 