apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-deploy-chart
spec:
  params:
    - name: charts-repo
    - name: charts-branch
    - name: charts-directory
    - name: config-repo
    - name: config-branch
    - name: config-directory
    - name: image-url
    - name: environment
    - name: cluster-name1
    - name: skip-deploy1
    - name: cluster-name2
    - name: skip-deploy2
    - name: cluster-name3
    - name: skip-deploy3
    - name: cluster-namespace
      default: 'opentoolchain'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-charts-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.charts-repo)
        - name: branch
          value: $(params.charts-branch)
        - name: directory-name
          value: $(params.charts-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-config-repo
      runAfter: [clone-charts-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.config-repo)
        - name: branch
          value: $(params.config-branch)
        - name: directory-name
          value: $(params.config-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: deploy-cluster-1
      runAfter: [clone-config-repo,clone-charts-repo]
      taskRef:
        name:  deploy-chart
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: image-url
          value: $(params.image-url)
        - name: image-tag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skip-deploy
          value: $(params.skip-deploy1)
        - name: cluster-name
          value: $(params.cluster-name1)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: deploy-cluster-2
      runAfter: [deploy-cluster-1]
      taskRef:
        name:  deploy-chart
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: image-url
          value: $(params.image-url)
        - name: image-tag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skip-deploy
          value: $(params.skip-deploy2)
        - name: cluster-name
          value: $(params.cluster-name2)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: deploy-cluster-3
      runAfter: [deploy-cluster-2]
      taskRef:
        name:  deploy-chart
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: image-url
          value: $(params.image-url)
        - name: image-tag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skip-deploy
          value: $(params.skip-deploy3)
        - name: cluster-name
          value: $(params.cluster-name3)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

