apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-dind
spec:
  params:
    - name: source-repo
    - name: source-branch
    - name: docker-file
    - name: run-base-image
      default: us.icr.io/opentoolchain/cd-build-base:nodejs12
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source-repo)
        - name: branch
          value: $(params.source-branch)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: build
      runAfter: [clone-source-repo]
      taskRef:
        name:  run-dind
      params:
        - name: docker-file
          value: $(params.docker-file)
        - name: run-base-image
          value: $(params.run-base-image)
        - name: branch
          value: $(params.source-branch)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 