apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-asoc
spec:
  params:
    - name: pipeline-pvc
    - name: source_repo
    - name: source_branch
    - name: source_directory
    - name: componentDockerImage
    - name: componentName
    - name: branchName
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directory-name
          value: $(params.source_directory)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: build
      runAfter: [clone-source-repo]
      taskRef:
        name: asoc-task
      params:
        - name: componentDockerImage
          value: $(params.componentDockerImage)
        - name: componentName
          value: $(params.componentName)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: send-slack
      runAfter: [build]
      taskRef:
        name: asoc-send-slack-task
      params:
        - name: componentName
          value: $(params.componentName)
        - name: branchName
          value: $(params.branchName)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc