apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-vault
spec:
  params:
    - name: pipeline-pvc
    - name: source_repo
    - name: source_branch
    - name: source_directory
    - name: imageUrl
    - name: imageName
    - name: imageTag
    - name: environment
    - name: skipBuild
    - name: skipVA
    - name: dockerFile
      default: ''
    - name: runBaseImage
      default: us.icr.io/opentoolchain/cd-build-base:nodejs10
    - name: artifactoryTokenBase64
      default: ''
    - name: artifactoryId
      default: ''
    - name: consoleAuthToken
      default: ''

  tasks:
    - name: clone-source-repo
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directoryName
          value: $(params.source_directory)
    - name: build
      runAfter: [clone-source-repo]
      taskRef:
        name:  run-base
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: runBaseImage
          value: $(params.runBaseImage)
        - name: dockerFile
          value: $(params.dockerFile)
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: artifactoryTokenBase64
          value: $(params.artifactoryTokenBase64)
        - name: artifactoryId
          value: $(params.artifactoryId)
        - name: consoleAuthToken
          value: $(params.consoleAuthToken)
    - name: build-va
      runAfter: [build]
      taskRef:
        name: run-va
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs10
        - name: dockerFile
          value: ''
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skipVA
          value: $(params.skipVA)
