apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-asoc
spec:
  params:
    - name: pipeline-pvc
    - name: source_repo
    - name: source_branch
    - name: source_directory
    - name: component_source_repo
    - name: component_directory
    - name: component_branch
    - name: componentName
  tasks:
    - name: clone-otc-deploy-repo
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directoryName
          value: $(params.source_directory)
    - name: clone-component-repo
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.component_source_repo)
        - name: branch
          value: $(params.component_branch)
        - name: directoryName
          value: $(params.component_directory)
    - name: build
      runAfter: [clone-source-repo]
      taskRef:
        name: maven-asoc-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: componentName
          value: $(params.componentName)
    - name: send-slack
      runAfter: [build]
      taskRef:
        name: asoc-send-slack-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: componentName
          value: $(params.componentName)
        - name: branchName
          value: $(params.component_branch)
    