apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-deploy-chart
spec:
  params:
    - name: pipeline-pvc
    - name: charts_repo
    - name: charts_branch
    - name: charts_directory
    - name: config_repo
    - name: config_branch
    - name: config_directory
    - name: imageUrl
    - name: imageName
    - name: imageTag
    - name: environment
    - name: clusterName1
      default: 'none'
    - name: skipDeploy1
    - name: clusterName2
      default: 'none'
    - name: skipDeploy2
    - name: clusterName3
      default: 'none'
    - name: skipDeploy3
    - name: clusterNamespace
      default: 'opentoolchain'

  tasks:
    - name: clone-charts-repo
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.charts_repo)
        - name: branch
          value: $(params.charts_branch)
        - name: directoryName
          value: $(params.charts_directory)
    - name: clone-config-repo
      runAfter: [clone-charts-repo]
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.config_repo)
        - name: branch
          value: $(params.config_branch)
        - name: directoryName
          value: $(params.config_directory)
    - name: deploy-cluster-$(params.clusterName1)
      runAfter: [clone-config-repo,clone-charts-repo]
      taskRef:
        name:  deploy-chart
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skipDeploy
          value: $(params.skipDeploy1)
        - name: clusterName
          value: $(params.clusterName1)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
    - name: deploy-cluster-$(params.clusterName2)
      runAfter: [deploy-cluster-$(params.clusterName1)]
      taskRef:
        name:  deploy-chart
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skipDeploy
          value: $(params.skipDeploy2)
        - name: clusterName
          value: $(params.clusterName2)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
    - name: deploy-cluster-$(params.clusterName3)
      runAfter: [deploy-cluster-$(params.clusterName2)]
      taskRef:
        name:  deploy-chart
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.charts_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skipDeploy
          value: $(params.skipDeploy3)
        - name: clusterName
          value: $(params.clusterName3)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
