apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-pii
spec:
  params:
    - name: source_repo
    - name: source_branch
    - name: source_directory
    - name: pii_repo
    - name: pii_branch
    - name: pii_directory
    - name: environment
    - name: runBaseImage
      default: us.icr.io/opentoolchain/cd-build-base:nodejs14
    - name: javaPattern
      default: 'false'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directory-name
          value: $(params.source_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-pii-repo
      runAfter: [clone-source-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.pii_repo)
        - name: branch
          value: $(params.pii_branch)
        - name: directory-name
          value: $(params.pii_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: pii-drop
      runAfter: [clone-pii-repo]
      taskRef:
        name:  run-pii
      params:
        - name: source_directory
          value: $(params.source_directory)
        - name: runBaseImage
          value: $(params.runBaseImage)
        - name: environment
          value: $(params.environment)
        - name: javaPattern
          value: $(params.javaPattern)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
