apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-open-cr
spec:
  params:
    - name: charts-repo
    - name: charts-branch
    - name: charts-directory
    - name: environment
    - name: deploy-clusters
    - name: sn-url
    - name: prod-repos
      default: 'None'
    - name: deploy-channel
      default: '#devops-otc-deployment'
    - name: toc-channel
      default: '#devops-cd-cie'
    - name: e2e-build-id
    - name: cr-priority
      default: "moderate"
    - name: cr-type
      default: "standard"
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-charts-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.charts-repo)
        - name: branch
          value: $(params.charts-branch)
        - name: directory-name
          value: $(params.charts-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: get-deployment-info
      runAfter: [clone-charts-repo]
      taskRef:
        name: deployment-information
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: prod-repos
          value: $(params.prod-repos)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: open-cr
      runAfter: [get-deployment-info]
      taskRef:
        name:  open-cr
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: environment
          value: $(params.environment)
        - name: deploy-clusters
          value: $(params.deploy-clusters)
        - name: sn-url
          value: $(params.sn-url)
        - name: deploy-channel
          value: $(params.deploy-channel)
        - name: toc-channel
          value: $(params.toc-channel)
        - name: e2e-build-id
          value: $(params.e2e-build-id)
        - name: cr-priority
          value: $(params.cr-priority)
        - name: cr-type
          value: $(params.cr-type)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

