apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-rolling-deployments
spec:
  params:
    - name: script-repo
    - name: script-branch
    - name: script-directory
    - name: regions
    - name: cluster-region
      default: "us-south"
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-script-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.script-repo)
        - name: branch
          value: $(params.script-branch)
        - name: directory-name
          value: $(params.script-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: rollout
      runAfter: [clone-script-repo]
      taskRef:
        name: rollout-task
      params:
        - name: script-directory
          value: $(params.script-directory)
        - name: regions
          value: $(params.regions)
        - name: cluster-region
          value: $(params.cluster-region)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
