apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-close-cr
spec:
  params:
    - name: charts-repo
    - name: charts-branch
    - name: charts-directory
    - name: environment
    - name: deploy-clusters
    - name: sn-url
    - name: deploy-channel
      default: '#devops-otc-deployment'
    - name: toc-channel
      default: '#devops-cd-cie'
    - name: e2e-build-id
    - name: e2e-application
      default: 'CD-OTC'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-charts-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.charts-repo)
        - name: branch
          value: $(params.charts-branch)
        - name: directory-name
          value: $(params.charts-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: close-cr
      runAfter: [clone-charts-repo]
      taskRef:
        name:  close-cr
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: environment
          value: $(params.environment)
        - name: deploy-clusters
          value: $(params.deploy-clusters)
        - name: sn-url
          value: $(params.sn-url)
        - name: deploy-channel
          value: $(params.deploy-channel)
        - name: toc-channel
          value: $(params.toc-channel)
        - name: e2e-build-id
          value: $(params.e2e-build-id)
        - name: e2e-application
          value: $(params.e2e-application)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

