apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-rolling-deployments
spec:
  params:
    - name: script_repo
    - name: script_branch
    - name: script_directory
    - name: regions
    - name: cluster_region
      default: "us-south"
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-script-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.script_repo)
        - name: branch
          value: $(params.script_branch)
        - name: directory-name
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: rollout
      runAfter: [clone-script-repo]
      taskRef:
        name: rollout-task
      params:
        - name: script_directory
          value: $(params.script_directory)
        - name: regions
          value: $(params.regions)
        - name: cluster_region
          value: $(params.cluster_region)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
