apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-hc
spec:
  params:
    - name: script_repo
    - name: script_branch
    - name: script_directory
    - name: config_repo
    - name: config_branch
    - name: config_directory
    - name: clusterName1
    - name: skipDeploy1
    - name: clusterName2
    - name: skipDeploy2
    - name: clusterName3
    - name: skipDeploy3
    - name: clusterNamespace
      default: 'opentoolchain'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-script-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.script_repo)
        - name: branch
          value: $(params.script_branch)
        - name: directory-name
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-config-repo
      runAfter: [clone-script-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.config_repo)
        - name: branch
          value: $(params.config_branch)
        - name: directory-name
          value: $(params.config_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: deploy-cluster-1
      runAfter: [clone-config-repo,clone-script-repo]
      taskRef:
        name:  run-hc
      params:
        - name: source_directory
          value: $(params.config_directory)
        - name: script_directory
          value: $(params.script_directory)
        - name: skipDeploy
          value: $(params.skipDeploy1)
        - name: clusterName
          value: $(params.clusterName1)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: deploy-cluster-2
      runAfter: [clone-config-repo,clone-script-repo]
      taskRef:
        name:  run-hc
      params:
        - name: source_directory
          value: $(params.config_directory)
        - name: script_directory
          value: $(params.script_directory)
        - name: skipDeploy
          value: $(params.skipDeploy2)
        - name: clusterName
          value: $(params.clusterName2)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: deploy-cluster-3
      runAfter: [clone-config-repo,clone-script-repo]
      taskRef:
        name:  run-hc
      params:
        - name: source_directory
          value: $(params.config_directory)
        - name: script_directory
          value: $(params.script_directory)
        - name: skipDeploy
          value: $(params.skipDeploy3)
        - name: clusterName
          value: $(params.clusterName3)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

