apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-maven-asoc
spec:
  params:
    - name: source-repo
    - name: source-branch
    - name: source-directory
    - name: component-source-repo
    - name: component-directory
    - name: component-branch
    - name: component-name
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-otc-deploy-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source-repo)
        - name: branch
          value: $(params.source-branch)
        - name: directory-name
          value: $(params.source-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-component-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.component-source-repo)
        - name: branch
          value: $(params.component-branch)
        - name: directory-name
          value: $(params.component-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: build
      runAfter: [clone-otc-deploy-repo, clone-component-repo]
      taskRef:
        name: maven-asoc-task
      params:
        - name: component-name
          value: $(params.component-name)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: send-slack
      runAfter: [build]
      taskRef:
        name: asoc-send-slack-task
      params:
        - name: component-name
          value: $(params.component-name)
        - name: branch-name
          value: $(params.component-branch)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    