apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-travis-worker-checker-eu-de
spec:
  params:
    - name: script-repo
    - name: script-branch
    - name: script-directory
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-script-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.script-repo)
        - name: branch
          value: $(params.script-branch)
        - name: directory-name
          value: $(params.script-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: tw-check-fra
      runAfter: [clone-script-repo]
      taskRef:
        name: travis-worker-check
      params:
        - name: script-directory
          value: $(params.script-directory)
        - name: regions
          value: fra
        - name: cluster-region
          value: eu-de
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc

