apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-asoc
spec:
  params:
    - name: source-repo
    - name: source-branch
    - name: source-directory
    - name: component-docker-image
    - name: component-name
    - name: branch-name
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source-repo)
        - name: branch
          value: $(params.source-branch)
        - name: directory-name
          value: $(params.source-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: build
      runAfter: [clone-source-repo]
      taskRef:
        name: asoc-task
      params:
        - name: component-docker-image
          value: $(params.component-docker-image)
        - name: component-name
          value: $(params.component-name)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: send-slack
      runAfter: [build]
      taskRef:
        name: asoc-send-slack-task
      params:
        - name: component-name
          value: $(params.component-name)
        - name: branch-name
          value: $(params.branch-name)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc