apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-ci
spec:
  params:
    - name: pipeline-pvc
    - name: source_repo
    - name: source_branch
    - name: source_directory
    - name: charts_repo
    - name: charts_branch
    - name: charts_directory
    - name: config_repo
    - name: config_branch
    - name: config_directory
    - name: imageUrl
    - name: imageName
    - name: imageTag
    - name: environment
    - name: clusterName
    - name: clusterNamespace
    - name: skipBuild
    - name: skipVA
    - name: skipDeploy
    - name: artifactoryTokenBas64
      default: ''
    - name: artifactoryId
      default: ''
    - name: consoleAuthToken
      default: ''

  tasks:
    - name: clone-source-repo
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directoryName
          value: $(params.source_directory)
    - name: clone-charts-repo
      runAfter: [clone-source-repo]
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.charts_repo)
        - name: branch
          value: $(params.charts_branch)
        - name: directoryName
          value: $(params.charts_directory)
    - name: clone-config-repo
      runAfter: [clone-charts-repo]
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.config_repo)
        - name: branch
          value: $(params.config_branch)
        - name: directoryName
          value: $(params.config_directory)
    - name: build
      runAfter: [clone-config-repo,clone-charts-repo]
      taskRef:
        name:  run-base
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs10
        - name: dockerFile
          value: ''
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: artifactoryTokenBas64
          value: $(params.artifactoryTokenBas64)
        - name: artifactoryId
          value: $(params.artifactoryId)
        - name: consoleAuthToken
          value: $(params.consoleAuthToken)
    - name: build-va
      runAfter: [build]
      taskRef:
        name: run-va
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs10
        - name: dockerFile
          value: ''
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skipVA
          value: $(params.skipVA)
    - name: deploy
      runAfter: [build-va]
      taskRef:
        name: deploy
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skipDeploy
          value: $(params.skipDeploy)
        - name: clusterName
          value: $(params.clusterName)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
