apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-deploy-info
spec:
  params:
    - name: charts_directory
    - name: prodRepos
      default: 'None'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: get-master-info
      taskRef:
        name: master-list
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: prodRepos
          value: $(params.prodRepos)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: get-deployment-info
      runAfter: [get-master-info]
      taskRef:
        name: deployment-list
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: prodRepos
          value: $(params.prodRepos)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

