apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-vbi
spec:
  params:
    - name: source_repo
    - name: source_branch
    - name: dockerFile
    - name: dockerUsername
    - name: registryScope
    - name: useUbi
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: build
      runAfter: [clone-source-repo]
      taskRef:
        name:  run-vbi
      params:
        - name: dockerFile
          value: $(params.dockerFile)
        - name: dockerUsername
          value: $(params.dockerUsername)
        - name: registryScope
          value: $(params.registryScope)
        - name: useUbi
          value: $(params.useUbi)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 