apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-open-cr
spec:
  params:
    - name: pipeline-pvc
    - name: charts_repo
    - name: charts_branch
    - name: charts_directory
    - name: environment
    - name: deployClusters
    - name: snUrl
    - name: prodRepos
      default: 'None'
    - name: deployChannel
      default: '#devops-otc-deployment'
    - name: tocChannel
      default: '#devops-cd-cie'

  tasks:
    - name: clone-charts-repo
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.charts_repo)
        - name: branch
          value: $(params.charts_branch)
        - name: directoryName
          value: $(params.charts_directory)
    - name: get-deployment-info
      runAfter: [clone-charts-repo]
      taskRef:
        name: deployment-information
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.charts_directory)
        - name: prodRepos
          value: $(params.prodRepos)
    - name: open-cr
      runAfter: [get-deployment-info]
      taskRef:
        name:  open-cr
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: source_directory
          value: $(params.charts_directory)
        - name: environment
          value: $(params.environment)
        - name: deployClusters
          value: $(params.deployClusters)
        - name: snUrl
          value: $(params.snUrl)
        - name: deployChannel
          value: $(params.deployChannel)
        - name: tocChannel
          value: $(params.tocChannel)
