apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-vbi
spec:
  params:
    - name: source_repo
    - name: source_branch
    - name: dockerFile
    - name: runBaseImage
      default: ibmcom/pipeline-base-image:2.8
    - name: dockerUsername
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: build
      runAfter: [clone-source-repo]
      taskRef:
        name:  run-vbi
      params:
        - name: dockerFile
          value: $(params.dockerFile)
        - name: runBaseImage
          value: $(params.runBaseImage)
        - name: dockerUsername
          value: $(params.dockerUsername)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 