apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-deploy-info
spec:
  params:
    - name: charts-directory
    - name: prod-repos
      default: 'None'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: get-master-info
      taskRef:
        name: master-list
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: prod-repos
          value: $(params.prod-repos)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: get-deployment-info
      runAfter: [get-master-info]
      taskRef:
        name: deployment-list
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: prod-repos
          value: $(params.prod-repos)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

