apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-deploy-info
spec:
  params:
    - name: charts_repo
    - name: charts_branch
    - name: charts_directory
    - name: environment
    - name: deployClusters
    - name: snUrl
    - name: prodRepos
      default: 'None'
    - name: deployChannel
      default: '#devops-otc-deployment'
    - name: tocChannel
      default: '#devops-cd-cie'
    - name: e2eBuildId
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: get-deployment-info
      taskRef:
        name: deployment-list
      params:
        - name: source_directory
          value: $(params.charts_directory)
        - name: prodRepos
          value: $(params.prodRepos)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

