apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-tag-deployment
spec:
  params:
    - name: charts-repo
    - name: charts-branch
    - name: charts-directory
    - name: prod-repos
      default: 'None'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-charts-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.charts-repo)
        - name: branch
          value: $(params.charts-branch)
        - name: directory-name
          value: $(params.charts-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: tag-deployment
      runAfter: [clone-charts-repo]
      taskRef:
        name: tag-deployment
      params:
        - name: source-directory
          value: $(params.charts-directory)
        - name: prod-repos
          value: $(params.prod-repos)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 