apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-hc
spec:
  params:
    - name: script-repo
    - name: script-branch
    - name: script-directory
    - name: config-repo
    - name: config-branch
    - name: config-directory
    - name: cluster-name1
    - name: skip-deploy1
    - name: cluster-name2
    - name: skip-deploy2
    - name: cluster-name3
    - name: skip-deploy3
    - name: cluster-namespace
      default: 'opentoolchain'
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-script-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.script-repo)
        - name: branch
          value: $(params.script-branch)
        - name: directory-name
          value: $(params.script-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-config-repo
      runAfter: [clone-script-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.config-repo)
        - name: branch
          value: $(params.config-branch)
        - name: directory-name
          value: $(params.config-directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: deploy-cluster-1
      runAfter: [clone-config-repo,clone-script-repo]
      taskRef:
        name:  run-hc
      params:
        - name: source-directory
          value: $(params.config-directory)
        - name: script-directory
          value: $(params.script-directory)
        - name: skip-deploy
          value: $(params.skip-deploy1)
        - name: cluster-name
          value: $(params.cluster-name1)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: deploy-cluster-2
      runAfter: [clone-config-repo,clone-script-repo]
      taskRef:
        name:  run-hc
      params:
        - name: source-directory
          value: $(params.config-directory)
        - name: script-directory
          value: $(params.script-directory)
        - name: skip-deploy
          value: $(params.skip-deploy2)
        - name: cluster-name
          value: $(params.cluster-name2)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: deploy-cluster-3
      runAfter: [clone-config-repo,clone-script-repo]
      taskRef:
        name:  run-hc
      params:
        - name: source-directory
          value: $(params.config-directory)
        - name: script-directory
          value: $(params.script-directory)
        - name: skip-deploy
          value: $(params.skip-deploy3)
        - name: cluster-name
          value: $(params.cluster-name3)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 

