apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ci
spec:
  params:
    - name: source_repo
    - name: source_branch
    - name: source_directory
    - name: charts_repo
    - name: charts_branch
    - name: charts_directory
    - name: config_repo
    - name: config_branch
    - name: config_directory
    - name: imageUrl
    - name: environment
    - name: clusterName
    - name: clusterNamespace
    - name: skipBuild
    - name: skipVA
    - name: skipDeploy
    - name: dockerFile
      default: ''
    - name: runBaseImage
      default: us.icr.io/opentoolchain/cd-build-base:nodejs12
    - name: artifactoryTokenBase64
      default: ''
    - name: artifactoryId
      default: ''
    - name: consoleAuthToken
      default: ''
    - name: helmOptions
      default: ''
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directory-name
          value: $(params.source_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-charts-repo
      runAfter: [clone-source-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.charts_repo)
        - name: branch
          value: $(params.charts_branch)
        - name: directory-name
          value: $(params.charts_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: clone-config-repo
      runAfter: [clone-charts-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.config_repo)
        - name: branch
          value: $(params.config_branch)
        - name: directory-name
          value: $(params.config_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc 
    - name: build
      runAfter: [clone-config-repo,clone-charts-repo]
      taskRef:
        name:  run-base
      params:
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: runBaseImage
          value: $(params.runBaseImage)
        - name: dockerFile
          value: $(params.dockerFile)
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: artifactoryTokenBase64
          value: $(params.artifactoryTokenBase64)
        - name: artifactoryId
          value: $(params.artifactoryId)
        - name: consoleAuthToken
          value: $(params.consoleAuthToken)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: build-va
      runAfter: [build]
      taskRef:
        name: run-va
      params:
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: runBaseImage
          value: us.icr.io/opentoolchain/cd-build-base:nodejs12
        - name: dockerFile
          value: ''
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skipVA
          value: $(params.skipVA)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: deploy
      runAfter: [build-va]
      taskRef:
        name: deploy
      params:
        - name: source_directory
          value: $(params.source_directory)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: ''
        - name: environment
          value: $(params.environment)
        - name: skipDeploy
          value: $(params.skipDeploy)
        - name: clusterName
          value: $(params.clusterName)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
        - name: helmOptions
          value: $(params.helmOptions)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
