  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cd-config
  data:
    # private-worker-service-binding-dev binding values
    SOURCE_REPO: "https://github.ibm.com/org-ids/private-worker-service.git"
    SOURCE_BRANCH:  "master"
    SOURCE_DIRECTORY: "private-worker-service"
    CHARTS_REPO: "https://github.ibm.com/org-ids/cd-pipeline-kubernetes.git"
    CHARTS_BRANCH: "master"
    CHARTS_DIRECTORY: "private-worker-service/cd-pipeline-kubernetes"
    CONFIG_REPO: "https://github.ibm.com/ids-env/devops-config.git"
    CONFIG_BRANCH: "master"
    CONFIG_DIRECTORY: "private-worker-service/devops-config"
    IMAGE_URL: "us.icr.io/opentoolchain/private-worker-service"
    ENVIRONMENT: "development"
    CLUSTERNAME: "otc-us-south-dev"
    CLUSTERNAMESPACE: "opentoolchain"
    SKIPBUILD: "false"
    SKIPVA: "true"
    SKIPDEPLOY: "false"
    # original config map values
    API: "https://cloud.ibm.com"
    REGION: "us-south"
    RESOURCE_GROUP: "f778a8021f114465aff0e39885cff51a"
    TOOLCHAIN_ID: "63189b8f-7c6f-4c17-9c3f-2481763314a4"
    IDS_USER: "idsorg"