apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-key-rotation-consumption
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-key-rotation-consumption
spec:
  triggers:
    - binding:
        name: trigger-binding-key-rotation-consumption
      template:
        name: trigger-template-key-rotation-consumption