apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-secret-rotation
spec:
  params:
    - name: script_repo
    - name: script_branch
    - name: script_directory
    - name: config_repo
    - name: config_branch
    - name: config_directory
    - name: environment
    - name: clusterNamespace
    - name: clusterName1
    - name: skipCluster1
    - name: clusterName2
    - name: skipCluster2
    - name: clusterName3
    - name: skipCluster3
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-script-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.script_repo)
        - name: branch
          value: $(params.script_branch)
        - name: directory-name
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: clone-config-repo
      runAfter: [clone-script-repo]
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.config_repo)
        - name: branch
          value: $(params.config_branch)
        - name: directory-name
          value: $(params.config_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: validate
      runAfter: [clone-config-repo]
      taskRef:
        name: validate-secret-rotation
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: open-cr
      runAfter: [validate]
      taskRef:
        name: open-cr-secret-rotation
      params:
        - name: environment
          value: $(params.environment)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: update-vault
      runAfter: [open-cr]
      taskRef:
        name: update-vault
      params:
        - name: environment
          value: $(params.environment)
        - name: config_directory
          value: $(params.config_directory)
        - name: script_directory
          value: $(params.script_directory) 
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: rolling-restart-cluster1
      runAfter: [update-vault]
      taskRef:
        name: rolling-restart
      params:
        - name: clusterName
          value: $(params.clusterName1)
        - name: skip
          value: $(params.skipCluster1)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
        - name: script_directory
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: rolling-restart-cluster2
      runAfter: [update-vault]
      taskRef:
        name: rolling-restart
      params:
        - name: clusterName
          value: $(params.clusterName2)
        - name: skip
          value: $(params.skipCluster2)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
        - name: script_directory
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: rolling-restart-cluster3
      runAfter: [update-vault]
      taskRef:
        name: rolling-restart
      params:
        - name: clusterName
          value: $(params.clusterName3)
        - name: skip
          value: $(params.skipCluster3)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
        - name: script_directory
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: update-otc-api
      runAfter: [rolling-restart-cluster1,rolling-restart-cluster2,rolling-restart-cluster3]
      taskRef:
        name: update-otc-api
      params:
        - name: config_directory
          value: $(params.config_directory)
        - name: environment
          value: $(params.environment)
        - name: script_directory
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: cleanup-vault
      runAfter: [update-otc-api]
      taskRef:
        name: cleanup-vault
      params:
        - name: environment
          value: $(params.environment)
        - name: config_directory
          value: $(params.config_directory)
        - name: script_directory
          value: $(params.script_directory) 
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: rolling-restart-cluster1-2
      runAfter: [cleanup-vault]
      taskRef:
        name: rolling-restart
      params:
        - name: clusterName
          value: $(params.clusterName1)
        - name: skip
          value: $(params.skipCluster1)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
        - name: script_directory
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: rolling-restart-cluster2-2
      runAfter: [cleanup-vault]
      taskRef:
        name: rolling-restart
      params:
        - name: clusterName
          value: $(params.clusterName2)
        - name: skip
          value: $(params.skipCluster2)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
        - name: script_directory
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: rolling-restart-cluster3-2
      runAfter: [cleanup-vault]
      taskRef:
        name: rolling-restart
      params:
        - name: clusterName
          value: $(params.clusterName3)
        - name: skip
          value: $(params.skipCluster3)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
        - name: script_directory
          value: $(params.script_directory)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: close-cr
      runAfter: [rolling-restart-cluster1-2,rolling-restart-cluster2-2,rolling-restart-cluster3-2]
      taskRef:
        name: close-cr-secret-rotation
      params:
        - name: environment
          value: $(params.environment)
        - name: cr_id
          value: $(tasks.open-cr.results.cr_id)
      workspaces:
      - name: output
        workspace: pipeline-pvc