apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-otc-api
spec:
  params:
    - name: environment
    - name: config_directory
    - name: script_directory
  stepTemplate:
    env:
      - name: PIPELINE_RUN_URL
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
      - name: ROLE_ID
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: VAULT_SIDEKICK_ROLE_ID
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: IDS_TOKEN
      - name: SECRET_ID
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: VAULT_SIDEKICK_SECRET_ID
      - name: REGION
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: REGION
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: DEPLOY_API_KEY
  workspaces:
  - name: output
    mountPath: /workspace 
  steps:
  - name: update-otc-api
    image: icr.io/continuous-delivery/pipeline/tekton/common-tools:2.0.0
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: ENVIRONMENT
        value: $(params.environment)
      - name: CONFIG_DIRECTORY
        value: $(params.config_directory)
      - name: SCRIPT_DIRECTORY
        value: $(params.script_directory)
      - name: BLADE_SECRET_PATH
        value: "pipeline.blade-pipeline-broker.vault.secretPaths"
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        set -e -o pipefail

        . ${SCRIPT_DIRECTORY}/scripts/rotation/rotate_api_secret.sh

        ibmcloud config --check-version=false
        ibmcloud plugin install -f container-service
        ibmcloud login --apikey ${API_KEY} -r ${REGION}

        blade_vault_path=$(get_vault_path "${CONFIG_DIRECTORY}/environments/${ENVIRONMENT}/values.yaml" ${BLADE_SECRET_PATH} blade-pipeline-broker)

        echo "blade vault path: ${blade_vault_path}"
        blade_tempfile=$(mktemp)
        read_vault_path ${blade_vault_path} ${blade_tempfile}

        secret_value=$(get_current_secret ${blade_tempfile})
        rm ${blade_tempfile}
        update_broker "${ENVIRONMENT}" "${secret_value}" "${blade_vault_path}"

