apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: validate-secret-rotation
spec:
  stepTemplate:
    env:
      - name: PIPELINE_TRIGGERING_USER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
      - name: NEW_IAM_API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: NEW_IAM_API_KEY
  workspaces:
  - name: output
    mountPath: /workspace 
  steps:
  - name: close-cr
    image: icr.io/continuous-delivery/pipeline/tekton/common-tools:2.0.0
    imagePullPolicy: IfNotPresent
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        if [ -z $NEW_IAM_API_KEY ]; then
          echo "NEW_IAM_API_KEY is not set"
          exit 1
        fi