
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rolling-restart-support-service
spec:
  params:
    - name: clusterName
    - name: clusterNamespace
    - name: script_directory
    - name: skip
  stepTemplate:
    env:
      - name: PIPELINE_RUN_URL
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
      - name: API
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: API
      - name: REGION
        valueFrom:
          configMapKeyRef:
            name: cd-config
            key: REGION
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: DEPLOY_API_KEY
  workspaces:
  - name: output
    mountPath: /workspace 
  steps:
  - name: rolling-restart
    image: icr.io/continuous-delivery/pipeline/tekton/common-tools:2.0.0
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: SCRIPT_DIRECTORY
        value: $(params.script_directory)
      - name: SKIP
        value: $(params.skip)
      - name: CLUSTER_NAME
        value: $(params.clusterName)
      - name: CLUSTER_NAMESPACE
        value: $(params.clusterNamespace)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        if [ "${SKIP}" == true ]; then
          echo "Skipping rolling restart $CLUSTER_NAME"
          exit 0
        fi

        ibmcloud config --check-version=false
        ibmcloud plugin install -f container-service

        ibmcloud login --apikey ${API_KEY} -r ${REGION}
        . ${SCRIPT_DIRECTORY}/scripts/rotation/rotate_api_secret.sh

        cluster_config ${CLUSTER_NAME}
        if [ $? -eq 0 ]; then
          restart_pods ${CLUSTER_NAMESPACE}
        else
          echo "result: $result"
          exit 1
        fi