apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-devx
spec:
  params:
    - name: environment
    - name: config_directory
    - name: script_directory
  stepTemplate:
    env:
      - name: PIPELINE_RUN_URL
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
      - name: ROLE_ID
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: VAULT_SIDEKICK_ROLE_ID
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: IDS_TOKEN
      - name: SECRET_ID
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: VAULT_SIDEKICK_SECRET_ID
  workspaces:
  - name: output
    mountPath: /workspace
  steps:
  - name: update-vault
    image: icr.io/continuous-delivery/pipeline/tekton/common-tools:2.0.0
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: ENVIRONMENT
        value: $(params.environment)
      - name: CONFIG_DIRECTORY
        value: $(params.config_directory)
      - name: SCRIPT_DIRECTORY
        value: $(params.script_directory)
      - name: DEVX_SECRET_PATH
        value: "pipeline.pipeline-support-service.vault.secretPaths"
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        set -e -o pipefail

        . ${SCRIPT_DIRECTORY}/scripts/rotation/rotate_api_secret.sh

        # update pipeline-support-service secret
        devx_vault_path=$(get_vault_path "${CONFIG_DIRECTORY}/environments/${ENVIRONMENT}/values.yaml" ${DEVX_SECRET_PATH} pipeline-support-service)
        echo "devx vault path: ${devx_vault_path}"
        #devx_tempfile=$(mktemp)
        #read_vault_path ${devx_vault_path} ${devx_tempfile}
        #save_backup ${devx_tempfile} ${devx_vault_path}
        #new_secret=$(generate_new_secret)
        #generate_new_devx_value ${devx_tempfile} ${new_secret}
        #updating_vault ${devx_tempfile} ${devx_vault_path}
        #rm ${devx_tempfile}
