apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-vault-consumption
spec:
  params:
    - name: environment
    - name: config_directory
    - name: script_directory
  stepTemplate:
    env:
      - name: PIPELINE_RUN_URL
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
      - name: ROLE_ID
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: VAULT_SIDEKICK_ROLE_ID
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: IDS_TOKEN
      - name: SECRET_ID
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: VAULT_SIDEKICK_SECRET_ID
      - name: NEW_IAM_API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: NEW_IAM_API_KEY
  workspaces:
  - name: output
    mountPath: /workspace 
  steps:
  - name: update-vault
    image: icr.io/continuous-delivery/pipeline/tekton/common-tools:2.0.0
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: ENVIRONMENT
        value: $(params.environment)
      - name: CONFIG_DIRECTORY
        value: $(params.config_directory)
      - name: SCRIPT_DIRECTORY
        value: $(params.script_directory)
      - name: CONSUMPTION_SECRET_PATH
        value: "pipeline.pipeline-consumption.vault.secretPaths"
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - | 
        set -e -o pipefail

        . ${SCRIPT_DIRECTORY}/scripts/rotation/rotate_api_secret.sh

        # update pipeline-consumption secret
        consumption_vault_path=$(get_vault_path "${CONFIG_DIRECTORY}/environments/${ENVIRONMENT}/values.yaml" ${CONSUMPTION_SECRET_PATH} pipeline-consumption)
        echo "pipeline-consumption vault path: ${consumption_vault_path}"
        consumption_tempfile=$(mktemp)
        read_vault_path ${consumption_vault_path} ${consumption_tempfile}
        save_backup ${consumption_tempfile} ${consumption_vault_path}
        generate_new_iam_api_key ${consumption_tempfile} ${NEW_IAM_API_KEY}
        updating_vault ${consumption_tempfile} ${consumption_vault_path}
        rm ${consumption_tempfile}