apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: close-cr-secret-rotation
spec:
  params:
    - name: environment
      default: 'development'
    - name: snUrl
      default: 'https://watson.service-now.com'
    - name: deployChannel
      default: '#devops-otc-deployment'
    - name: cr_id
  stepTemplate:
    env:
      - name: PIPELINE_TRIGGERING_USER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: DEPLOY_API_KEY
      - name: SN_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: SN_TOKEN
      - name: SLACK_DEPLOY_HOOK
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: SLACK_DEPLOY_HOOK
  workspaces:
  - name: output
    mountPath: /workspace 
  steps:
  - name: close-cr
    image: icr.io/continuous-delivery/pipeline/tekton/common-tools:2.0.0
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: DEPLOY_TARGET
        value: $(params.environment)
      - name: SN_URL
        value: $(params.snUrl)
      - name: ENVIRONMENT
        value: $(params.environment)
      - name: CR_ID
        value: $(params.cr_id)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        if [ $ENVIRONMENT == "development" ]; then
          echo "Skip CR closing for development environment"
          exit 0
        fi
        if [ $ENVIRONMENT == "dev" ]; then
          echo "Skip CR closing for dev environment"
          exit 0
        fi
        ibmcloud config --check-version=false
        echo Logging into ibmcloud
        ibmcloud login -a cloud.ibm.com -r us-south --apikey ${API_KEY}
        BEARER=$( ibmcloud iam oauth-tokens --output json | jq -r .iam_token )

        CR_CLOSE_CATEGORY=successful

        echo "Closing ServiceNow change request $CR_ID ..."

        cat - >"$TMP" <<HERE
        {
            "closecategory": "$CR_CLOSE_CATEGORY",
            "closenotes": "DEPLOYMENT finished.",
            "actualendtime": "now"
        }
        HERE

        RESPONSE=$(curl --request PUT -H "Authorization:Bearer $SN_TOKEN" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            --data "@$TMP" "$SN_URL/api/ibmwc/change/$CR_ID/close" \
            --silent --show-error)

        RESULT=$(jq ".result | select (.!=null)" <<< "$RESPONSE")

        if [[ ! "$RESULT" ]]; then
            echo "Failed: $RESPONSE"
            exit 1
        fi

        echo "ServiceNow change request closed: $SN_URL/nav_to.do?uri=change_request.do?sysparm_query=number=$CR_ID"

        SN_ICON=":delivery-pipeline:"
        
        NOTICE_TEXT=${SN_CLOSE_NOTICE_TEXT:="The deployment in ${ENVIRONMENT} has concluded."}

        ICON=${SN_ICON:=":mario-pipe-5339:"}
        SLACK_USERNAME=${SN_SLACK_USERNAME:="Deployment Notification"}

        cat << EOF > message.json
        {
          "channel": "${SLACK_DEPLOY_CHANNEL}",
          "username": "${SLACK_USERNAME}",
          "icon_emoji": "${ICON}",
          "text": "${NOTICE_TEXT} \n"
        }
        EOF
        echo Posting message to "${SLACK_DEPLOY_CHANNEL}" channel
        #Post to slack deployment channel
        curl -X POST -H "Content-Type: application/json" \
            -d @message.json \
            ${SLACK_DEPLOY_HOOK}
