{{- define "pipeline.common.ingress.tpl" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
{{ template "common.metadata" . }}
{{- if .Values.ingress }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ include "common.annote" .Values.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ template "common.fullname" $ }}.{{ .Values.basedomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "common.fullname" $ }}
          servicePort: 80
  tls:
  - hosts:
    - {{ template "common.fullname" $ }}.{{ .Values.basedomain }}
    secretName: {{ .Values.basedomain }}
{{- end -}}
{{- end -}}
{{- define "pipeline.common.ingress" -}}
{{- template "common.util.merge" (append . "pipeline.common.ingress.tpl") -}}
{{- end -}}
