{{- define "pipeline.common.statefulset.tpl" -}}
apiVersion: apps/v1
kind: StatefulSet 
{{ template "common.metadata" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "common.name" . }} 
  template:
    serviceName: {{ template "common.fullname" . }}
    metadata:
      labels:
        app: {{ template "common.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      terminationGracePeriodSeconds:  {{.Values.terminationGracePeriodSeconds | default 60}}
      containers:
      -
{{ include "common.container.tpl" . | indent 8 }}
{{- end -}}
{{- define "pipeline.common.statefulset" -}}
{{- template "common.util.merge" (append . "pipeline.common.statefulset.tpl") -}}
{{- end -}}
