{{- define "pipeline.common.statefulset.tpl" -}}
apiVersion: apps/v1beta2
kind: StatefulSet 
{{ template "common.metadata" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "common.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      -
{{ include "common.container.tpl" . | indent 8 }}
{{- end -}}
{{- define "pipeline.common.statefulset" -}}
{{- template "common.util.merge" (append . "pipeline.common.statefulset.tpl") -}}
{{- end -}}
