{{- template "pipeline.common.ingress" (list . "pipeline.ingress") -}}
{{- define "pipeline.ingress" -}}
apiVersion: extensions/v1beta1
kind: Ingress
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
spec:
  rules:
  - host: {{ template "common.fullname" $ }}.{{ .Values.basedomain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "common.fullname" $ }} 
          servicePort: 80
  tls:
  - hosts:
    - {{ template "common.fullname" $ }}.{{ .Values.basedomain }}
    secretName: {{ template "common.fullname" $ }}-tls
{{- end -}}
