apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.fullname" . }} 
spec:
  podSelector:
    matchLabels:
      app: {{ template "common.fullname" . }} 
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 100.64.0.0/10
        - 192.168.0.0/16
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
