apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "common.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "common.fullname" . }}
