apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.fullname" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname" . }}-admin-role-nonResourceURLSs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-role-nonResourceURLSs
subjects:
- kind: ServiceAccount
  name: {{ template "common.fullname" . }} 
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname" . }}-admin-role-resourceURLSs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-role-resourceURLSs
subjects:
- kind: ServiceAccount
  name: {{ template "common.fullname" . }} 
  namespace: {{ .Release.Namespace }}
