apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: travis-worker-registry
spec:
  podSelector:
    matchLabels:
      app: {{ template "common.fullname" . }} 
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
           app: travis-registry
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
