apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-dev
spec:
  params:
    - name: IAM_API_KEY
      value: $(params.IAM_API_KEY_1651315)
    - name: WEBHOOK_SECRET_UPDATER
      value: $(params.WEBHOOK_SECRET_UPDATER_DEV)
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
      value: $(params.WEBHOOK_TOKEN_SECRET_UPDATER_DEV)
    - name: REDIS_CERT
      value: $(params.REDIS_DEV_CERT)
    - name: REDIS_URL
      value: $(params.REDIS_DEV_PRIMARY_URL)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-au-syd
spec:
  params:
    - name: IAM_API_KEY
      value: $(params.IAM_API_KEY_1416501)
    - name: WEBHOOK_SECRET_UPDATER
      value: $(params.WEBHOOK_SECRET_UPDATER_AU_SYD)
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
      value: $(params.WEBHOOK_TOKEN_SECRET_UPDATER_AU_SYD)
    - name: REDIS_CERT
      value: $(params.REDIS_AU_SYD_CERT)
    - name: REDIS_URL
      value: $(params.REDIS_AU_SYD_PRIMARY_URL)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-us-south
spec:
  params:
    - name: IAM_API_KEY
      value: $(params.IAM_API_KEY_1416501)
    - name: WEBHOOK_SECRET_UPDATER
      value: $(params.WEBHOOK_SECRET_UPDATER_US_SOUTH)
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
      value: $(params.WEBHOOK_TOKEN_SECRET_UPDATER_US_SOUTH)
    - name: REDIS_CERT
      value: $(params.REDIS_US_SOUTH_CERT)
    - name: REDIS_URL
      value: $(params.REDIS_US_SOUTH_PRIMARY_URL)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-eu-de
spec:
  params:
    - name: IAM_API_KEY
      value: $(params.IAM_API_KEY_1416501)
    - name: WEBHOOK_SECRET_UPDATER
      value: $(params.WEBHOOK_SECRET_UPDATER_EU_DE)
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
      value: $(params.WEBHOOK_TOKEN_SECRET_UPDATER_EU_DE)
    - name: REDIS_CERT
      value: $(params.REDIS_EU_DE_CERT)
    - name: REDIS_URL
      value: $(params.REDIS_EU_DE_PRIMARY_URL)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-eu-gb
spec:
  params:
    - name: IAM_API_KEY
      value: $(params.IAM_API_KEY_1416501)
    - name: WEBHOOK_SECRET_UPDATER
      value: $(params.WEBHOOK_SECRET_UPDATER_EU_GB)
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
      value: $(params.WEBHOOK_TOKEN_SECRET_UPDATER_EU_GB)
    - name: REDIS_CERT
      value: $(params.REDIS_EU_GB_CERT)
    - name: REDIS_URL
      value: $(params.REDIS_EU_GB_PRIMARY_URL)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-jp-tok
spec:
  params:
    - name: IAM_API_KEY
      value: $(params.IAM_API_KEY_1416501)
    - name: WEBHOOK_SECRET_UPDATER
      value: $(params.WEBHOOK_SECRET_UPDATER_JP_TOK)
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
      value: $(params.WEBHOOK_TOKEN_SECRET_UPDATER_JP_TOK)
    - name: REDIS_CERT
      value: $(params.REDIS_JP_TOK_CERT)
    - name: REDIS_URL
      value: $(params.REDIS_JP_TOK_PRIMARY_URL)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-us-east
spec:
  params:
    - name: IAM_API_KEY
      value: $(params.IAM_API_KEY_1416501)
    - name: WEBHOOK_SECRET_UPDATER
      value: $(params.WEBHOOK_SECRET_UPDATER_US_EAST)
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
      value: $(params.WEBHOOK_TOKEN_SECRET_UPDATER_US_EAST)
    - name: REDIS_CERT
      value: $(params.REDIS_US_EAST_CERT)
    - name: REDIS_URL
      value: $(params.REDIS_US_EAST_PRIMARY_URL)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-eu-fr2
spec:
  params:
    - name: IAM_API_KEY
      value: $(params.IAM_API_KEY_1416501)
    - name: WEBHOOK_SECRET_UPDATER
      value: $(params.WEBHOOK_SECRET_UPDATER_EU_FR2)
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
      value: $(params.WEBHOOK_TOKEN_SECRET_UPDATER_EU_FR2)
    - name: REDIS_CERT
      value: $(params.REDIS_EU_FR2_CERT)
    - name: REDIS_URL
      value: $(params.REDIS_EU_FR2_PRIMARY_URL)
