apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-bss-credential-rotate
spec:
  workspaces:
    - name: pipeline-pvc
  params:
    - name: block-until-verified
    - name: cr-backout-plan
    - name: cr-description
    - name: cr-purpose
    - name: cr-skip
    - name: ctask-description
    - name: ctask-short-description
    - name: gpfs-deployments
    - name: otc-deployments
    - name: remove-from-glb-during-update
    - name: restart-pws
    - name: slack-finish-description
    - name: slack-icon
    - name: slack-start-description
    - name: slack-username
    - name: vault-name
    - name: verification-string
    - name: zone-names
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-repo
      workspaces:
        - name: output
          workspace: pipeline-pvc
      params:
        - name: repository
          value: https://github.ibm.com/org-ids/otc-secret-updater
        - name: branch
          value: master
    - name: bss-switch
      runAfter: [clone-repo]
      taskRef:
        name: task-bss-credential-rotate
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
      params:
        - name: block-until-verified
          value: $(params.block-until-verified)
        - name: cr-backout-plan
          value: $(params.cr-backout-plan)
        - name: cr-description
          value: $(params.cr-description)
        - name: cr-purpose
          value: $(params.cr-purpose)
        - name: cr-skip
          value: $(params.cr-skip)
        - name: ctask-description
          value: $(params.ctask-description)
        - name: ctask-short-description
          value: $(params.ctask-short-description)
        - name: gpfs-deployments
          value: $(params.gpfs-deployments)
        - name: otc-deployments
          value: $(params.otc-deployments)
        - name: remove-from-glb-during-update
          value: $(params.remove-from-glb-during-update)
        - name: restart-pws
          value: $(params.restart-pws)
        - name: slack-finish-description
          value: $(params.slack-finish-description)
        - name: slack-icon
          value: $(params.slack-icon)
        - name: slack-start-description
          value: $(params.slack-start-description)
        - name: slack-username
          value: $(params.slack-username)
        - name: vault-name
          value: $(params.vault-name)
        - name: verification-string
          value: $(params.verification-string)
        - name: zone-names
          value: $(params.zone-names)
