apiVersion: tekton.dev/v1beta1
kind: Pipeline
  metadata:
    name: pipeline-secrets-update
  spec:
    workspaces:
      - name: pipeline-pvc
    params:
      - name: selected-region
      - name: selected-secret
      - name: add-missing-secrets
      - name: block-until-verified
      - name: cr-assigned-to
      - name: cr-skip
      - name: ctask-description
      - name: ctask-short-description
      - name: ctask-test-results
      - name: gpfs-deployments
      - name: otc-backup-deployments
      - name: otc-deployments
      - name: remove-from-glb-during-update
      - name: restart-pws
      - name: secrets-separator
      - name: slack-username
      - name: sn-region
      - name: sn-url
      - name: vault-name
      - name: vault-path
      - name: verification-string
      - name: zone-names
    tasks:
      - name: clone-repo
        taskRef:
          name: git-clone-repo
        workspaces:
          - name: output
            workspace: pipeline-pvc
        params:
          - name: repository
            value: "https://github.ibm.com/org-ids/otc-secret-updater" ------ Need to change repo to match
          - name: branch
            value: master
      - name: create-cr
        runAfter:
          - clone-repo
        taskRef:
          name: task-create-cr
        workspaces:
          - name: task-pvc
            workspace: pipeline-pvc
        params:
          - name: cr-assigned-to
            value: $(params.cr-assigned-to)
          - name: cr-backout-plan
            value: "Restore old $(params.selected-secret) token"
          - name: cr-description
            value: "Updating $(params.selected-secret) token for $(params.selected-region)"
          - name: cr-purpose
            value: "Required to keep secrets up to date"
          - name: cr-skip
            value: $(params.cr-skip)
          - name: ctask-description
            value: "To rotate the $(params.selected-secret) Token"
          - name: ctask-short-description
            value: $(params.ctask-short-description)
          - name: ctask-test-results
            value: $(params.ctask-test-results)
          - name: slack-icon
            value: ":delivery-pipeline:"
          - name: slack-start-description
            value: "Starting update for the $(params.selected-secret) token in $(params.selected-region)"
          - name: slack-username
            value: $(params.slack-username)
          - name: sn-region
            value: $(params.sn-region)
          - name: sn-url
            value: $(params.sn-url)
          - name: zone-names ---- To remove and include within python
            value: $(params.zone-names)
      - name: secrets-update
        runAfter:
          - create-cr
        taskRef:
          name: task-update-secrets
        workspaces:
          - name: task-pvc
            workspace: pipeline-pvc
        params:
          - name: add-missing-secrets
            value: $(params.add-missing-secrets)
          - name: block-until-verified
            value: $(params.block-until-verified)
          - name: gpfs-deployments
            value: $(params.gpfs-deployments)
          - name: otc-backup-deployments
            value: $(params.otc-backup-deployments)
          - name: otc-deployments
            value: $(params.otc-deployments)
          - name: remove-from-glb-during-update
            value: $(params.remove-from-glb-during-update)
          - name: restart-pws
            value: $(params.restart-pws)
          - name: secrets-separator
            value: $(params.secrets-separator)
          - name: vault-name
            value: $(params.vault-name)
          - name: vault-path
            value: $(params.vault-path)
          - name: verification-string
            value: $(params.verification-string)
          - name: zone-names
            value: $(params.zone-names)
