apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-update-secrets
spec:
  params:
    - name: zone-names
    - name: remove-from-glb-during-update
    - name: gpfs-deployments
    - name: otc-backup-deployments
    - name: otc-deployments
    - name: vault-name
    - name: vault-path
    - name: restart-pws
    - name: secrets-separator
    - name: add-missing-secrets
    - name: block-until-verified
    - name: verification-string
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: update-secrets
      image: ibmcom/pipeline-base-image
      imagePullPolicy: Always
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: cd-secret
              key: GIT_TOKEN
        - name: GLB_IAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: cd-secret
              key: GLB_IAM_API_KEY
        - name: IAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: cd-secret
              key: IAM_API_KEY
        - name: SECRETS
          valueFrom:
            secretKeyRef:
              name: cd-secret
              key: SECRETS
        - name: VAULT_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: cd-secret
              key: VAULT_ROLEID
        - name: VAULT_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: cd-secret
              key: VAULT_SECRETID
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail
          apt-get -y update
          apt-get -y install python3
          echo
          cd /workspace
          zonesArray=$(echo $(params.zone-names) | tr "," "\n")
          for zone in $zonesArray
          do
              echo
              echo "============================================================================================"
              echo
              otc_deployments=$(params.otc-backup-deployments)
              gpfs_deployments=""
              if [[ $zone != *"backup"* ]]; then
                  otc_deployments=$(params.otc-deployments)
                  gpfs_deployments=$(params.gpfs-deployments)
              fi
              set -x
              python3 ./update_secrets.py $(params.vault-name) $zone --otc_deployments=$otc_deployments --gpfs_deployments=$gpfs_deployments --restart_pws=$(params.restart-pws) --add_missing_secrets=$(params.add-missing-secrets) --remove_from_glb_during_update=$(params.remove-from-glb-during-update) --verification_string=$(params.verification-string) --block_until_verified=$(params.block-until-verified) --secrets_separator=$(params.secrets-separator) --vault_path=$(params.vault-path) || { exit 1; }
              set +x
          done
