apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-secrets_update
spec:
  params:
    - name: add-missing-secrets
    - name: block-until-verified
    - name: dockerconfigjson
    - name: gpfs-deployments
    - name: otc-backup-deployments
    - name: otc-deployments
    - name: remove-from-glb-during-update
    - name: restart-pws
    - name: secrets-separator
    - name: cr-assigned-to
    - name: cr-skip
    - name: sn-region
    - name: ctask-test-results
    - name: sn-token
    - name: sn-url
    - name: vault-name
    - name: vault-path
    - name: verification-string
    - name: zone-names
    - name: CR_BACKOUT_PLAN
    - name: CR_DESCRIPTION
    - name: CR_PURPOSE
    - name: CTASK_DESCRIPTION
    - name: CTASK_SHORT_DESCRIPTION
    - name: SLACK_FINISH_DESCRIPTION
      default: Finished update of secrets
    - name: SLACK_ICON
    - name: SLACK_START_DESCRIPTION
      default: Starting update of secrets
    - name: VAULT_ROLEID
    - name: VAULT_SECRETID
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.IAM_API_KEY)
        GIT_TOKEN: $(params.GIT_TOKEN)
        GLB_IAM_API_KEY: $(params.GLB_IAM_API_KEY)
        IAM_API_KEY: $(params.IAM_API_KEY)
        SECRETS: $(params.SECRETS)
        SLACK_WEBHOOK: $(params.SLACK_WEBHOOK)
        SN_TOKEN: $(params.sn-token)
        VAULT_ROLEID: $(params.VAULT_ROLEID)
        VAULT_SECRETID: $(params.VAULT_SECRETID)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: otc-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: otc-sa
      imagePullSecrets:
        - name: otc-registry-secret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-secrets-update
        serviceAccountName: otc-sa
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: add-missing-secrets
            value: $(params.add-missing-secrets)
          - name: block-until-verified
            value: $(params.block-until-verified)
          - name: cr-assigned-to
            value: $(params.cr-assigned-to)
          - name: cr-backout-plan
            value: $(params.CR_BACKOUT_PLAN)
          - name: cr-description
            value: $(params.CR_DESCRIPTION)
          - name: cr-purpose
            value: $(params.CR_PURPOSE)
          - name: cr-skip
            value: $(params.cr-skip)
          - name: ctask-description
            value: $(params.CTASK_DESCRIPTION)
          - name: ctask-short-description
            value: $(params.CTASK_SHORT_DESCRIPTION)
          - name: ctask-test-results
            value: $(params.ctask-test-results)
          - name: gpfs-deployments
            value: $(params.gpfs-deployments)
          - name: otc-backup-deployments
            value: $(params.otc-backup-deployments)
          - name: otc-deployments
            value: $(params.otc-deployments)
          - name: remove-from-glb-during-update
            value: $(params.remove-from-glb-during-update)
          - name: restart-pws
            value: $(params.restart-pws)
          - name: secrets-separator
            value: $(params.secrets-separator)
          - name: slack-finish-description
            value: $(params.SLACK_FINISH_DESCRIPTION)
          - name: slack-icon
            value: $(params.SLACK_ICON)
          - name: slack-start-description
            value: $(params.SLACK_START_DESCRIPTION)
          - name: slack-username
            value: CD Secrets Updater
          - name: sn-region
            value: $(params.sn-region)
          - name: sn-url
            value: $(params.sn-url)
          - name: vault-name
            value: $(params.vault-name)
          - name: vault-path
            value: $(params.vault-path)
          - name: verification-string
            value: $(params.verification-string)
          - name: zone-names
            value: $(params.zone-names)
