apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-bss-credential-rotate
spec:
  params:
    - name: block-until-verified
      default: "false"
    - name: dockerconfigjson
    - name: gpfs-deployments
    - name: otc-deployments
    - name: remove-from-glb-during-update
      default: "false"
    - name: skip-CHG-creation
    - name: vault-name
    - name: verification-string
    - name: zone-names
    - name: GIT_TOKEN
    - name: IAM_API_KEY
    - name: CR_BACKOUT_PLAN
    - name: CR_DESCRIPTION
    - name: CR_PURPOSE
    - name: CTASK_DESCRIPTION
    - name: CTASK_SHORT_DESCRIPTION
    - name: SLACK_FINISH_DESCRIPTION
    - name: SLACK_ICON
    - name: SLACK_START_DESCRIPTION
    - name: SLACK_USERNAME
    - name: WEBHOOK_SECRET_UPDATER
    - name: WEBHOOK_TOKEN_SECRET_UPDATER
    - name: BSS_JSON
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.IAM_API_KEY)
        WEBHOOK_SECRET_UPDATER: $(params.WEBHOOK_SECRET_UPDATER)
        WEBHOOK_TOKEN_SECRET_UPDATER: $(params.WEBHOOK_TOKEN_SECRET_UPDATER)
        BSS_JSON: $(params.BSS_JSON)
        GIT_TOKEN: $(params.GIT_TOKEN)
        IAM_API_KEY: $(params.IAM_API_KEY)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: otc-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: otc-sa
      imagePullSecrets:
        - name: otc-registry-secret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-bss-credential-rotate
        serviceAccountName: otc-sa
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: block-until-verified
            value: $(params.block-until-verified)
          - name: cr-backout-plan
            value: $(params.CR_BACKOUT_PLAN)
          - name: cr-description
            value: $(params.CR_DESCRIPTION)
          - name: cr-purpose
            value: $(params.CR_PURPOSE)
          - name: cr-skip
            value: $(params.skip-CHG-creation)
          - name: ctask-description
            value: $(params.CTASK_DESCRIPTION)
          - name: ctask-short-description
            value: $(params.CTASK_SHORT_DESCRIPTION)
          - name: gpfs-deployments
            value: $(params.gpfs-deployments)
          - name: otc-deployments
            value: $(params.otc-deployments)
          - name: remove-from-glb-during-update
            value: $(params.remove-from-glb-during-update)
          - name: restart-pws
            value: "false"
          - name: slack-finish-description
            value: $(params.SLACK_FINISH_DESCRIPTION)
          - name: slack-icon
            value: $(params.SLACK_ICON)
          - name: slack-start-description
            value: $(params.SLACK_START_DESCRIPTION)
          - name: slack-username
            value: $(params.SLACK_USERNAME)
          - name: vault-name
            value: $(params.vault-name)
          - name: verification-string
            value: $(params.verification-string)
          - name: zone-names
            value: $(params.zone-names)
