apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-agent-pipeline
spec:
  params:
    - name: componentRepo
      description: The component repo url
    - name: componentRevision
      description: The component revision
    - name: accountApiKey1416501
      description: api key for prod cluster / CR
    - name: accountApiKey1308775
      description: api key for docker build machine
    - name: idsToken
      description: the ids token to use to clone repos
    - name: imageUrl
      description: The config repo url
    - name: dockerhubPassword
      description: password for docker hub
    - name: envTag
      description: tag for the final dockerhub image
    - name: skipVA
      description: skip VA 
  workspaces:
  - name: pipeline-pvc
  tasks:
  - name: build
    taskRef:
      name:  build-agent
    params:
      - name: componentRepo
        value: $(params.componentRepo)
      - name: componentRevision
        value: $(params.componentRevision)
      - name: idsToken
        value: $(params.idsToken)
      - name: imageUrl
        value: $(params.imageUrl)
      - name: accountApiKey1308775
        value: $(params.accountApiKey1308775)
      - name: accountApiKey1416501
        value: $(params.accountApiKey1416501)
      - name: dockerhubPassword
        value: $(params.dockerhubPassword)
      - name: pipelinePVC
        value: $(params.pipelinePVC)
      - name: envTag
        value: $(params.envTag)
      - name: skipVA
        value: $(params.skipVA)
    workspaces:
    - name: task-pvc
      workspace: pipeline-pvc 
  