apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: open-cr-managed-worker
spec:
  params:
    - name: region
      default: 'development'
    - name: snUrl
      default: 'https://watsontest.service-now.com'
    - name: cr_priority
      default: "moderate"
    - name: cr_type
      default: "standard"
    - name: update_agent
    - name: update_kata
  results:
    - name: cr_id
      description: the cr id that was created by the task
  stepTemplate:
    env:
      - name: PIPELINE_TRIGGERING_USER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
      - name: SN_TOKEN
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: SN_TOKEN
  workspaces:
  - name: output
    mountPath: /workspace 
  steps:
  - name: open-cr
    image: icr.io/continuous-delivery/pipeline/tekton/common-tools:2.0.0
    imagePullPolicy: IfNotPresent
    env:
      - name: HOME
        value: "/root"
      - name: DEPLOY_TARGET
        value: $(params.region)
      - name: SN_URL
        value: $(params.snUrl)
      - name: REGION
        value: $(params.region)
      - name: CR_PRIORITY
        value: $(params.cr_priority)
      - name: CR_TYPE
        value: $(params.cr_type)
      - name: UPDATE_AGENT
        value: $(params.update_agent)
      - name: UPDATE_KATA
        value: $(params.update_kata)
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        if [ $REGION == "development" ] || [ $REGION == "dev" ]; then
          echo "Skip CR creation for $REGION environment"
          CR_ID="no cr"
          echo -n $CR_ID | tee $(results.cr_id.path)
          exit 0
        fi

        set -e

        if [ -z ${CR_TYPE} ]; then
          CR_TYPE="standard"
        fi
        if [ -z ${CR_PRIORITY} ]; then
          CR_PRIORITY="moderate"
        fi

        SYSTEM="continuous-delivery-pipeline"
        CRN="crn:v1:bluemix:public::$REGION::::"

        if [[ "$PIPELINE_TRIGGERING_USER" =~ .+@.+\..+ && "$PIPELINE_TRIGGERING_USER" != "idsorg@us.ibm.com" ]]; then
            ASSIGNED_TO="$PIPELINE_TRIGGERING_USER"
        else
            ASSIGNED_TO="$(git log -1 --pretty=format:'%ae')"
        fi

        # set CR time for 3 hour
        S_DATE=$(( $(date +%s) + 5 ))
        E_DATE=$(( $(date +%s) + 4*10800 ))

        description=""
        purpose=""

        if [[ UPDATE_KATA == "true" ]]
        then
          TEMP_TARGET_KATA=$(yq --yaml-output '.spec.template.spec.containers[0].image' kata-deploy/config/200-kata-deploy.yaml | sed -e 's/^"//' -e 's/"$//')    
          read -ra tar <<<"$TEMP_TARGET_KATA"
          TARGET_KATA=${tar[0]}
          CURRENT_KATA=$(kubectl get ds -n kube-system kata-deploy -o json | jq -r .spec.template.spec.containers[0].image | sed -e 's/^"//' -e 's/"$//')
          purpose+="Keep kata up to date --- "
          description+="Update kata from version $CURRENT_KATA to $TARGET_KATA --- "
        fi

        if [[ UPDATE_AGENT == "true" ]]
        then
          TARGET_AGENT=$(kubectl -n tekton-pipelines get deployment private-worker-agent -ojson | jq -r '.spec.template.spec.containers[].image' | sed -e 's/^"//' -e 's/"$//')
          CURRENT_AGENT=$(yq --yaml-output '.spec.template.spec.containers[0].image' <(curl https://private-worker-service.${REGION}.${TARGET_DOMAIN}/install) | grep pipeline-private-worker | sed -e 's/^"//' -e 's/"$//')
          purpose+="Keep agent up to date --- "
          description+="Update agent from version $CURRENT_AGENT to $TARGET_AGENT --- "
        fi

        description+="Using the pipeline https://cloud.ibm.com/devops/pipelines/tekton/0dc0ca3b-f881-4d43-91ee-b0306632f81e?env_id=ibm:yp:us-south"

        export TMP=/tmp/tmp_$$.json

        # tag message adds link to ServiceNow query using deploy commit hash in the description field
        cat - >"$TMP" <<HERE
        {
          "assignedto": "$ASSIGNED_TO",
          "system": "$SYSTEM",
          "impact": "N/A",
          "outageduration": "0 00:00:00",
          "priority": "${CR_PRIORITY}",
          "environment": "$CRN",
          "purpose": "$purpose",
          "description": "$description",
          "backoutplan": "Retry update",
          "plannedstart": "$(date -u -d@${S_DATE} "+%Y-%m-%d %H:%M:%S")",
          "plannedend": "$(date -u -d@${E_DATE} "+%Y-%m-%d %H:%M:%S")", 
          "deploymentready": "yes",
          "type": "${CR_TYPE}"
        }
        HERE

        echo "Opening CR with:"
        cat "$TMP"

        RESPONSE=$(curl --request POST -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            --data "@$TMP" "$SN_URL/api/ibmwc/v2/change/create" \
            --silent --show-error)

        echo "RESPONSE: ${RESPONSE}"
        CR_ID=$(jq --raw-output ".result.number | select (.!=null)" <<< "$RESPONSE")
        echo "CR ID: ${CR_ID}"
        echo "$SN_URL/nav_to.do?uri=change_request.do?sysparm_query=number=${CR_ID}"

        sleep 10
        RESPONSE=$(curl --request PUT -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            --data "$PAYLOAD" "$SN_URL/api/ibmwc/v2/change/$CR_ID/implement" \
            --silent --show-error)
        
        echo "Checking ServiceNow change request state..."

        sleep 10

        RESPONSE=$(curl -H "Authorization:Bearer $SN_TOKEN" \
            -H "updated_by: $ASSIGNED_TO" \
            -H "Accept:application/json" \
            -H "Content-Type:application/json" \
            "$SN_URL/api/ibmwc/v2/change/$CR_ID/read" \
            --silent --show-error)

        CR_STATE=$(jq --raw-output ".result.state | select (.!=null)" <<< "$RESPONSE")
        echo "ServiceNow change request is in $CR_STATE state."

        echo -n $CR_ID | tee $(results.cr_id.path)
