apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: componentRevision
      description: the branch for the git repo
    - name: envTag
      description: tag for the final dockerhub image
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: otc-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: otc-sa
      imagePullSecrets:
      - name: otc-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: agentbuild-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: agentbuild-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "pipeline-template"
      spec:
        pipelineRef:
            name: build-agent-pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: agentbuild-$(uid)-pvc
        serviceAccountName: otc-sa
        params:
          - name: componentRepo
            value: https://github.ibm.com/org-ids/private-worker-agent.git
          - name: componentRevision
            value: $(params.componentRevision)
          - name: idsToken
            value: $(params.IDS_TOKEN)
          - name: imageUrl
            value: us.icr.io/devopsotc/private-worker-agent
          - name: accountApiKey1308775
            value: $(params.API_KEY_1308775)
          - name: accountApiKey1416501
            value: $(params.API_KEY_1416501)
          - name: dockerhubPassword
            value: $(params.DOCKERHUB_PASSWORD)
          - name: envTag
            value: $(params.envTag)
          - name: skipVA
            value: $(params.skipVA)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: agent-0.10.1-pipeline-binding-dev
spec:
  params:
    - name: componentRevision
      value: 0.10.1_tekton
    - name: envTag
      value: -dev
    - name: skipVA
      value: "true"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-agent-0.10.1-listener-dev
spec:
  triggers:
    - binding:
        name: agent-0.10.1-pipeline-binding-dev
      template:
        name: pipeline-template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: agent-0.11.2-pipeline-binding-prod
spec:
  params:
    - name: componentRevision
      value: integration
    - name: envTag
      value: ""
    - name: skipVA
      value: "false"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-agent-0.11.2-listener-prod
spec:
  triggers:
    - binding:
        name: agent-0.11.2-pipeline-binding-prod
      template:
        name: pipeline-template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: agent-0.11.2-pipeline-binding-dev
spec:
  params:
    - name: componentRevision
      value: master
    - name: envTag
      value: -dev
    - name: skipVA
      value: "true"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-agent-0.11.2-listener-dev
spec:
  triggers:
    - binding:
        name: agent-0.11.2-pipeline-binding-dev
      template:
        name: pipeline-template
