apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: componentRevision
      description: the branch for the git repo
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: otc-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: otc-sa
      imagePullSecrets:
      - name: otc-registry-secret
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipeline-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "pipeline-template"
      spec:
        pipelineRef:
            name: build-agent-pipeline
        serviceAccount: otc-sa
        params:
          - name: componentRepo
            value: https://github.ibm.com/org-ids/private-worker-agent.git
          - name: componentRevision
            value: $(params.componentRevision)
          - name: idsToken
            value: $(params.IDS_TOKEN)
          - name: imageUrl
            value: us.icr.io/opentoolchain/private-worker-agent
          - name: accountApiKey1308775
            value: $(params.API_KEY_1308775)
          - name: accountApiKey1416501
            value: $(params.API_KEY_1416501)
          - name: dockerhubPassword
            value: $(params.DOCKERHUB_PASSWORD)
          - name: pipelinePVC
            value: pipeline-$(uid)-pvc
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: agent-0.7.0-pipeline-binding-dev
spec:
  params:
    - name: componentRevision
      value: master
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: agent-0.10.1-pipeline-binding-dev
spec:
  params:
    - name: componentRevision
      value: 0.10.1-dev
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-agent-0.7.0-listener-dev
spec:
  triggers:
    - binding:
        name: agent-0.7.0-pipeline-binding-dev
      template:
        name: pipeline-template
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-agent-0.10.1-listener-dev
spec:
  triggers:
    - binding:
        name: agent-0.10.1-pipeline-binding-dev
      template:
        name: pipeline-template