Storage: 20Gi
StorageClass: ibmc-block-gold
ui:
  enabled: false 
uiService:
  enabled: false 
  type: "ClusterIP" 
uiIngress:
  enabled: false 
  annotations: {}
  hosts: [ devops-build.us-south.containers.mybluemix.net ] 
  tls: 
    - hosts:
      - devops-build.us-south.containers.mybluemix.net
      secretName: devops-build

