apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: helm3-update-plugin-au-syd-trigger-dev
spec:
  params:
    - name: region
    - name: environment
    - name: clusterName1
    - name: skipDeploy1
    - name: clusterName2
    - name: skipDeploy2
    - name: clusterName3
    - name: skipDeploy3
    # CD integration
    - name: api
      description: the ibmcloud api
      default: https://cloud.ibm.com

  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        API: $(params.api)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY_1416501)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: helm3-update-plugin-au-syd-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce

    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        #generateName: $(params.source_branch)-base-run
        name: helm3-update-plugin-au-syd-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "helm3-update-plugin-au-syd-trigger-dev"
      spec:
        pipelineRef:
          name: pipeline-helm3-update-plugin
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: helm3-update-plugin-au-syd-$(uid)-pvc
        serviceAccountName: docker-build-sa
        params:
          - name: region
            value: $(params.region)
          - name: environment
            value: $(params.environment)
          - name: clusterName1
            value: $(params.clusterName1)
          - name: clusterName2
            value: $(params.clusterName2)
          - name: clusterName3
            value: $(params.clusterName3)
          - name: skipDeploy1
            value: $(params.skipDeploy1)
          - name: skipDeploy2
            value: $(params.skipDeploy2)
          - name: skipDeploy3
            value: $(params.skipDeploy3)
          - name: pluginName
            value: $(params.pluginName)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: helm3-update-plugin-au-syd-binding-dev
spec:
  params:
    - name: region
      value: "au-syd"
    - name: environment
      value: "prod-au-syd"
    - name: clusterName1
      value: otc-pw-syd01-prod
    - name: clusterName2
      value: otc-pw-syd04-prod
    - name: clusterName3
      value: otc-pw-syd05-prod
    - name: skipDeploy1
      value: "false"
    - name: skipDeploy2
      value: "false"
    - name: skipDeploy3
      value: "false"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: helm3-update-plugin-au-syd-dev
spec:
  triggers:
    - binding:
        name: helm3-update-plugin-au-syd-binding-dev
      template:
        name: helm3-update-plugin-au-syd-trigger-dev
