apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-helm3-update
spec:
  params:
    - name: region
    - name: environment
    - name: clusterName1
    - name: skipDeploy1
    - name: clusterName2
    - name: skipDeploy2
    - name: clusterName3
    - name: skipDeploy3
    - name: pluginName
  workspaces:
    - name: pipeline-pvc
  tasks:
    - name: open-cr
      taskRef:
        name: open-cr-helm3-plugin
      params:
        - name: region
          value: $(params.region)
        - name: environment
          value: $(params.environment)
        - name: pluginName
          value: $(params.pluginName)
        - name: clusterName
          value: $(params.clusterName1)
      workspaces:
      - name: output
        workspace: pipeline-pvc
    - name: update-helm3-plugin-1
      runAfter: [open-cr]
      taskRef:
        name: update-helm3-plugin
      params:
        - name: region
          value: $(params.region)
        - name: clusterName
          value: $(params.clusterName1)
        - name: skipDeploy
          value: $(params.skipDeploy1)
        - name: pluginName
          value: $(params.pluginName)
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
    - name: update-helm3-plugin-2
      runAfter: [open-cr]
      taskRef:
        name: update-helm3-plugin
      params:
        - name: region
          value: $(params.region)
        - name: clusterName
          value: $(params.clusterName2)
        - name: skipDeploy
          value: $(params.skipDeploy2)
        - name: pluginName
          value: $(params.pluginName)
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
    - name: update-helm3-plugin-3
      runAfter: [open-cr]
      taskRef:
        name: update-helm3-plugin
      params:
        - name: region
          value: $(params.region)
        - name: clusterName
          value: $(params.clusterName3)
        - name: skipDeploy
          value: $(params.skipDeploy3)
        - name: pluginName
          value: $(params.pluginName)
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
    - name: close-cr
      runAfter: [update-helm3-plugin-1,update-helm3-plugin-2,update-helm3-plugin-3]
      taskRef:
        name: close-cr-helm3-plugin
      params:
        - name: region
          value: $(params.region)
        - name: environment
          value: $(params.environment)
        - name: cr_id
          value: $(tasks.open-cr.results.cr_id)
      workspaces:
      - name: output
        workspace: pipeline-pvc

