apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.fullname" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "common.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ template "common.fullname" . }}"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
