apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-psp-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-privileged-psp-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:masters
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:default
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:ibm-observe
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:ibm-services-system
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:tekton-pipelines
